# Generated by Django 6.0.2 on 2026-02-28 06:41

import apps.cases.models.log
import apps.core.filesystem.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_archived", models.BooleanField(default=False, verbose_name="是否已建档")),
                (
                    "filing_number",
                    models.CharField(
                        blank=True,
                        help_text="格式: {年份}_{案件类型}_{AJ}_{序号}",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="建档编号",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="案件名称")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "在办"), ("closed", "已结案")],
                        default="active",
                        max_length=32,
                        verbose_name="案件状态",
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True, verbose_name="收案日期")),
                ("effective_date", models.DateField(blank=True, null=True, verbose_name="生效日期")),
                ("specified_date", models.DateField(blank=True, null=True, verbose_name="指定日期")),
                ("cause_of_action", models.CharField(blank=True, max_length=128, null=True, verbose_name="案由")),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="涉案金额"
                    ),
                ),
                (
                    "preservation_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="财产保全金额"
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("civil", "民事"),
                            ("administrative", "行政"),
                            ("criminal", "刑事"),
                            ("execution", "申请执行"),
                            ("bankruptcy", "破产"),
                        ],
                        default="civil",
                        max_length=32,
                        null=True,
                        verbose_name="案件类型",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_trial", "一审"),
                            ("second_trial", "二审"),
                            ("enforcement", "执行"),
                            ("labor_arbitration", "劳动仲裁"),
                            ("administrative_review", "行政复议"),
                            ("private_prosecution", "自诉"),
                            ("investigation", "侦查"),
                            ("prosecution_review", "审查起诉"),
                            ("retrial_first", "重审一审"),
                            ("retrial_second", "重审二审"),
                            ("apply_retrial", "申请再审"),
                            ("rehearing_first", "再审一审"),
                            ("rehearing_second", "再审二审"),
                            ("review", "提审"),
                            ("death_penalty_review", "死刑复核程序"),
                            ("petition", "申诉"),
                            ("apply_protest", "申请抗诉"),
                            ("petition_protest", "申诉抗诉"),
                        ],
                        max_length=64,
                        null=True,
                        verbose_name="当前阶段",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件",
                "verbose_name_plural": "案件",
            },
        ),
        migrations.CreateModel(
            name="CaseAccessGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "案件访问授权",
                "verbose_name_plural": "案件访问授权",
            },
        ),
        migrations.CreateModel(
            name="CaseAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "案件指派",
                "verbose_name_plural": "案件指派",
            },
        ),
        migrations.CreateModel(
            name="CaseChat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("feishu", "飞书"),
                            ("dingtalk", "钉钉"),
                            ("wechat_work", "企业微信"),
                            ("telegram", "Telegram"),
                            ("slack", "Slack"),
                        ],
                        default="feishu",
                        max_length=32,
                        verbose_name="平台",
                    ),
                ),
                ("chat_id", models.CharField(max_length=128, verbose_name="群聊ID")),
                ("name", models.CharField(max_length=255, verbose_name="群名")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "owner_id",
                    models.CharField(
                        blank=True,
                        help_text="飞书用户的open_id或其他平台的用户标识符",
                        max_length=64,
                        null=True,
                        verbose_name="群主ID",
                    ),
                ),
                (
                    "owner_verified",
                    models.BooleanField(default=False, help_text="群主设置是否已验证", verbose_name="群主已验证"),
                ),
                (
                    "owner_verified_at",
                    models.DateTimeField(
                        blank=True, help_text="群主设置验证成功的时间", null=True, verbose_name="群主验证时间"
                    ),
                ),
                (
                    "creation_audit_log",
                    models.JSONField(
                        default=dict, help_text="群聊创建过程的详细日志,包含群主设置信息", verbose_name="创建审计日志"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "案件群聊",
                "verbose_name_plural": "案件群聊",
            },
        ),
        migrations.CreateModel(
            name="CaseFilingNumberSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(unique=True, verbose_name="年份")),
                ("next_value", models.IntegerField(default=1, verbose_name="下一个序号")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "案件建档编号序列",
                "verbose_name_plural": "案件建档编号序列",
            },
        ),
        migrations.CreateModel(
            name="CaseFolderBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "folder_path",
                    models.CharField(
                        help_text="绑定的本地或网络文件夹路径", max_length=1000, verbose_name="文件夹路径"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="绑定时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "案件文件夹绑定",
                "verbose_name_plural": "案件文件夹绑定",
            },
        ),
        migrations.CreateModel(
            name="CaseLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="日志内容")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建日期")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改日期")),
            ],
            options={
                "verbose_name": "案件日志",
                "verbose_name_plural": "案件日志",
            },
        ),
        migrations.CreateModel(
            name="CaseLogAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        storage=apps.core.filesystem.storage.KeepOriginalNameStorage(),
                        upload_to="case_logs/",
                        validators=[apps.cases.models.log.validate_log_attachment],
                        verbose_name="相关文书",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
            ],
            options={
                "verbose_name": "案件日志附件",
                "verbose_name_plural": "案件日志附件",
            },
        ),
        migrations.CreateModel(
            name="CaseLogVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="历史内容")),
                ("version_at", models.DateTimeField(auto_now_add=True, verbose_name="版本时间")),
            ],
            options={
                "verbose_name": "案件日志版本",
                "verbose_name_plural": "案件日志版本",
            },
        ),
        migrations.CreateModel(
            name="CaseMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("party", "当事人材料"), ("non_party", "非当事人材料")],
                        max_length=32,
                        verbose_name="材料大类",
                    ),
                ),
                ("type_name", models.CharField(max_length=64, verbose_name="类型名称")),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[("our", "我方当事人材料"), ("opponent", "对方当事人材料")],
                        max_length=32,
                        null=True,
                        verbose_name="当事人方向",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "案件材料",
                "verbose_name_plural": "案件材料",
            },
        ),
        migrations.CreateModel(
            name="CaseMaterialGroupOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("party", "当事人材料"), ("non_party", "非当事人材料")],
                        max_length=32,
                        verbose_name="材料大类",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[("our", "我方当事人材料"), ("opponent", "对方当事人材料")],
                        max_length=32,
                        null=True,
                        verbose_name="当事人方向",
                    ),
                ),
                ("sort_index", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "案件材料分组顺序",
                "verbose_name_plural": "案件材料分组顺序",
            },
        ),
        migrations.CreateModel(
            name="CaseMaterialType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("party", "当事人材料"), ("non_party", "非当事人材料")],
                        max_length=32,
                        verbose_name="材料大类",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="类型名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "案件材料类型",
                "verbose_name_plural": "案件材料类型",
            },
        ),
        migrations.CreateModel(
            name="CaseNumber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=128, verbose_name="案号")),
                ("is_active", models.BooleanField(default=False, verbose_name="是否已生效")),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "案件案号",
                "verbose_name_plural": "案件案号",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseParty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "legal_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plaintiff", "原告"),
                            ("defendant", "被告"),
                            ("third", "第三人"),
                            ("applicant", "申请人"),
                            ("respondent", "被申请人"),
                            ("criminal_defendant", "被告人"),
                            ("victim", "被害人"),
                            ("appellant", "上诉人"),
                            ("appellee", "被上诉人"),
                            ("orig_plaintiff", "原审原告"),
                            ("orig_defendant", "原审被告"),
                            ("orig_third", "原审第三人"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="诉讼地位",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件当事人",
                "verbose_name_plural": "案件当事人",
            },
        ),
        migrations.CreateModel(
            name="CaseTemplateBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "binding_source",
                    models.CharField(
                        choices=[("auto_recommended", "自动推荐"), ("manual_bound", "手动绑定")],
                        default="auto_recommended",
                        max_length=20,
                        verbose_name="绑定来源",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="绑定时间")),
            ],
            options={
                "verbose_name": "案件模板绑定",
                "verbose_name_plural": "案件模板绑定",
            },
        ),
        migrations.CreateModel(
            name="ChatAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE_START", "开始创建"),
                            ("CREATE_SUCCESS", "创建成功"),
                            ("CREATE_FAILED", "创建失败"),
                            ("OWNER_SET", "设置群主"),
                            ("OWNER_VERIFY", "验证群主"),
                            ("OWNER_RETRY", "重试群主设置"),
                            ("OWNER_SET_FAILED", "群主设置失败"),
                            ("CONFIG_ERROR", "配置错误"),
                        ],
                        help_text="执行的操作类型",
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "details",
                    models.JSONField(default=dict, help_text="操作的详细信息,以JSON格式存储", verbose_name="操作详情"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="操作发生的时间", verbose_name="时间戳"),
                ),
                ("success", models.BooleanField(default=True, help_text="操作是否成功执行", verbose_name="操作成功")),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="操作失败时的错误信息", verbose_name="错误信息"),
                ),
                (
                    "external_chat_id",
                    models.CharField(
                        blank=True, help_text="群聊的外部ID,便于查询", max_length=128, verbose_name="群聊ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("feishu", "飞书"),
                            ("dingtalk", "钉钉"),
                            ("wechat_work", "企业微信"),
                            ("telegram", "Telegram"),
                            ("slack", "Slack"),
                        ],
                        default="feishu",
                        help_text="群聊平台",
                        max_length=32,
                        verbose_name="平台",
                    ),
                ),
                (
                    "audit_version",
                    models.CharField(
                        default="1.0", help_text="审计日志格式版本", max_length=16, verbose_name="审计版本"
                    ),
                ),
            ],
            options={
                "verbose_name": "群聊审计日志",
                "verbose_name_plural": "群聊审计日志",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SupervisingAuthority",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="名称")),
                (
                    "authority_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("investigation", "侦查机关"),
                            ("prosecution", "审查起诉机关"),
                            ("trial", "审理机构"),
                            ("detention", "当前关押地点"),
                        ],
                        default="trial",
                        max_length=32,
                        null=True,
                        verbose_name="性质",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "主管机关",
                "verbose_name_plural": "主管机关",
                "ordering": ["created_at"],
            },
        ),
    ]
