# Generated by Django 6.0.2 on 2026-03-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_initial"),
        ("contracts", "0002_add_order_to_finalized_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="contracts.contract",
                verbose_name="关联合同",
            ),
        ),
    ]
