# Generated by Django 6.0.2 on 2026-03-19 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_cascade_delete_case_on_contract_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseFolderScanSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "扫描中"),
                            ("classifying", "分类中"),
                            ("completed", "已完成"),
                            ("staged", "已导入附件"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("task_id", models.CharField(blank=True, default="", max_length=64, verbose_name="DjangoQ任务ID")),
                ("progress", models.PositiveIntegerField(default=0, verbose_name="进度百分比")),
                ("current_file", models.CharField(blank=True, default="", max_length=255, verbose_name="当前文件")),
                ("result_payload", models.JSONField(blank=True, default=dict, verbose_name="结果载荷")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_scan_sessions",
                        to="cases.case",
                        verbose_name="案件",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_folder_scan_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件文件夹扫描会话",
                "verbose_name_plural": "案件文件夹扫描会话",
                "indexes": [
                    models.Index(fields=["case", "-created_at"], name="cases_casef_case_id_5e6940_idx"),
                    models.Index(fields=["status", "-created_at"], name="cases_casef_status_6e121f_idx"),
                ],
            },
        ),
    ]
