# Generated by Django 6.0.2 on 2026-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_casefolderscansession"),
    ]

    operations = [
        migrations.AddField(
            model_name="casenumber",
            name="document_name",
            field=models.CharField(
                blank=True,
                help_text="如：民事判决书、民事调解书、执行证书等",
                max_length=128,
                null=True,
                verbose_name="文书名称",
            ),
        ),
    ]
