# Generated by Django 6.0.2 on 2026-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_add_case_number_document_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="casenumber",
            name="document_content",
            field=models.TextField(
                blank=True, help_text="从裁判文书自动提取的判决/调解主文内容", null=True, verbose_name="执行依据主文"
            ),
        ),
        migrations.AddField(
            model_name="casenumber",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="上传PDF格式的裁判文书，用于自动提取执行依据主文",
                null=True,
                upload_to="case_documents/%Y/%m/",
                verbose_name="裁判文书文件",
            ),
        ),
    ]
