# Generated by Django 6.0.2 on 2026-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_add_case_number_document_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="casenumber",
            name="execution_cutoff_date",
            field=models.DateField(
                blank=True,
                help_text="申请执行事项中利息计算截至日期；为空时优先按案件“指定日期”计算，未填写指定日期时按当天计算",
                null=True,
                verbose_name="执行事项截止日",
            ),
        ),
        migrations.AddField(
            model_name="casenumber",
            name="execution_date_inclusion",
            field=models.CharField(
                choices=[
                    ("both", "起止日都计入"),
                    ("start_only", "仅计入起始日"),
                    ("end_only", "仅计入截止日"),
                    ("neither", "起止日都不计入"),
                ],
                default="both",
                help_text="利息计算参数：起止日期是否计入",
                max_length=16,
                verbose_name="日期包含方式",
            ),
        ),
        migrations.AddField(
            model_name="casenumber",
            name="execution_manual_text",
            field=models.TextField(
                blank=True,
                help_text="有值时模板生成优先使用该文本",
                null=True,
                verbose_name="申请执行事项（手工最终文本）",
            ),
        ),
        migrations.AddField(
            model_name="casenumber",
            name="execution_paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="用于按抵扣顺序重算未付款项，默认 0",
                max_digits=14,
                verbose_name="已付款金额",
            ),
        ),
        migrations.AddField(
            model_name="casenumber",
            name="execution_use_deduction_order",
            field=models.BooleanField(
                default=False,
                help_text="启用后按文书条款中的抵扣顺序处理已付款",
                verbose_name="启用抵扣顺序",
            ),
        ),
        migrations.AddField(
            model_name="casenumber",
            name="execution_year_days",
            field=models.PositiveSmallIntegerField(
                choices=[(360, "360天"), (365, "365天"), (0, "按实际天数")],
                default=360,
                help_text="利息计算参数：360 / 365 / 按实际天数",
                verbose_name="年基准天数",
            ),
        ),
    ]
