# Generated by Django 6.0.2 on 2026-03-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_casenumber_execution_request_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casechat",
            options={"verbose_name": "群聊", "verbose_name_plural": "群聊"},
        ),
        migrations.AlterModelOptions(
            name="caselog",
            options={"verbose_name": "日志", "verbose_name_plural": "日志"},
        ),
        migrations.AlterModelOptions(
            name="caselogattachment",
            options={"verbose_name": "日志附件", "verbose_name_plural": "日志附件"},
        ),
    ]
