# Generated by Django 6.0.4 on 2026-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_rename_is_archived_to_is_filed"),
        ("contracts", "0014_material_category_archive_additions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="case",
            name="cases_case_is_arch_591fe0_idx",
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["is_filed"], name="cases_case_is_file_bd9fe6_idx"),
        ),
    ]
