# Generated by Django 6.0.4 on 2026-04-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_remove_case_cases_case_is_arch_591fe0_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caselog",
            name="source_subfolder",
            field=models.CharField(
                blank=True,
                default="",
                help_text="邮件往来导入时记录的来源子文件夹路径，用于去重",
                max_length=500,
                verbose_name="来源子文件夹",
            ),
        ),
    ]
