# Generated by Django 6.0.4 on 2026-04-17 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_caselogattachment_archive_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caselog',
            name='cases_casel_case_id_81df24_idx',
        ),
        migrations.AddField(
            model_name='caselog',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='log_type',
            field=models.CharField(choices=[('manual', '人工记录'), ('progress', '进展记录'), ('material', '材料记录'), ('reminder', '提醒记录'), ('document', '文书记录'), ('system', '系统记录')], default='manual', max_length=24, verbose_name='日志类型'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='source',
            field=models.CharField(choices=[('case', '案件'), ('contract', '合同'), ('material', '材料'), ('reminder', '提醒'), ('automation', '自动化'), ('system', '系统')], default='case', max_length=24, verbose_name='日志来源'),
        ),
        migrations.AlterField(
            model_name='caselogversion',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_log_versions', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddIndex(
            model_name='caselog',
            index=models.Index(fields=['case', '-is_pinned', '-created_at'], name='cases_casel_case_id_26adc1_idx'),
        ),
        migrations.AddIndex(
            model_name='caselog',
            index=models.Index(fields=['log_type'], name='cases_casel_log_typ_806582_idx'),
        ),
        migrations.AddIndex(
            model_name='caselog',
            index=models.Index(fields=['source'], name='cases_casel_source_eda8b6_idx'),
        ),
    ]
