# Generated by Django 6.0.4 on 2026-04-17 22:18

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_remove_caselog_cases_casel_case_id_81df24_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caselog',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日志时间'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='stage',
            field=models.CharField(blank=True, choices=[('first_trial', '一审'), ('second_trial', '二审'), ('enforcement', '执行'), ('labor_arbitration', '劳动仲裁'), ('administrative_review', '行政复议'), ('private_prosecution', '自诉'), ('investigation', '侦查'), ('prosecution_review', '审查起诉'), ('retrial_first', '重审一审'), ('retrial_second', '重审二审'), ('apply_retrial', '申请再审'), ('rehearing_first', '再审一审'), ('rehearing_second', '再审二审'), ('review', '提审'), ('death_penalty_review', '死刑复核程序'), ('petition', '申诉'), ('apply_protest', '申请抗诉'), ('petition_protest', '申诉抗诉')], max_length=64, null=True, verbose_name='审理阶段'),
        ),
        migrations.AddIndex(
            model_name='caselog',
            index=models.Index(fields=['case', '-logged_at', '-created_at'], name='cases_casel_case_id_1acf4c_idx'),
        ),
    ]
