# Generated by Django 6.0.4 on 2026-04-22 07:08

from pathlib import PurePosixPath

from django.db import migrations, models


def migrate_cases_relative_path(apps, schema_editor):
    """回填 CaseFolderBinding.relative_path：从绝对路径中提取相对合同文件夹的路径."""
    CaseFolderBinding = apps.get_model("cases", "CaseFolderBinding")
    ContractFolderBinding = apps.get_model("contracts", "ContractFolderBinding")

    for binding in CaseFolderBinding.objects.filter(relative_path="").select_related(
        "case__contract"
    ):
        case = binding.case
        if not case or not case.contract_id:
            continue

        contract = case.contract
        try:
            contract_binding = ContractFolderBinding.objects.get(contract_id=contract.id)
        except ContractFolderBinding.DoesNotExist:
            continue

        if not contract_binding.folder_path:
            continue

        case_path = PurePosixPath(binding.folder_path)
        contract_path = PurePosixPath(contract_binding.folder_path)

        if case_path.is_relative_to(contract_path):
            binding.relative_path = str(case_path.relative_to(contract_path))
            binding.save(update_fields=["relative_path"])


def reverse_migrate_cases_relative_path(apps, schema_editor):
    """反向迁移：清空 relative_path 字段."""
    CaseFolderBinding = apps.get_model("cases", "CaseFolderBinding")
    CaseFolderBinding.objects.filter(relative_path__gt="").update(relative_path="")


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_add_source_subfolder_to_caselog"),
        ("contracts", "0020_add_unsigned_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="casefolderbinding",
            name="relative_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="相对合同文件夹的路径，如 2026.04.22-[民商事]某某案",
                max_length=500,
                verbose_name="相对路径",
            ),
        ),
        migrations.RunPython(
            migrate_cases_relative_path,
            reverse_migrate_cases_relative_path,
        ),
    ]
