# Generated by Django 6.0.4 on 2026-04-25 07:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_add_inode_and_relative_path"),
        ("contracts", "0023_remove_closed_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCase",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("is_filed", models.BooleanField(default=False, verbose_name="是否已建档")),
                (
                    "filing_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="格式: {年份}_{案件类型}_{AJ}_{序号}",
                        max_length=50,
                        null=True,
                        verbose_name="建档编号",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="案件名称")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "在办"), ("closed", "已结案")],
                        default="active",
                        max_length=32,
                        verbose_name="案件状态",
                    ),
                ),
                ("start_date", models.DateField(blank=True, editable=False, verbose_name="收案日期")),
                ("effective_date", models.DateField(blank=True, null=True, verbose_name="生效日期")),
                ("specified_date", models.DateField(blank=True, null=True, verbose_name="指定日期")),
                ("cause_of_action", models.CharField(blank=True, max_length=128, null=True, verbose_name="案由")),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="涉案金额"
                    ),
                ),
                (
                    "preservation_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="财产保全金额"
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("civil", "民事"),
                            ("administrative", "行政"),
                            ("criminal", "刑事"),
                            ("execution", "申请执行"),
                            ("bankruptcy", "破产"),
                        ],
                        default="civil",
                        max_length=32,
                        null=True,
                        verbose_name="案件类型",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_trial", "一审"),
                            ("second_trial", "二审"),
                            ("enforcement", "执行"),
                            ("labor_arbitration", "劳动仲裁"),
                            ("administrative_review", "行政复议"),
                            ("private_prosecution", "自诉"),
                            ("investigation", "侦查"),
                            ("prosecution_review", "审查起诉"),
                            ("retrial_first", "重审一审"),
                            ("retrial_second", "重审二审"),
                            ("apply_retrial", "申请再审"),
                            ("rehearing_first", "再审一审"),
                            ("rehearing_second", "再审二审"),
                            ("review", "提审"),
                            ("death_penalty_review", "死刑复核程序"),
                            ("petition", "申诉"),
                            ("apply_protest", "申请抗诉"),
                            ("petition_protest", "申诉抗诉"),
                        ],
                        max_length=64,
                        null=True,
                        verbose_name="当前阶段",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contracts.contract",
                        verbose_name="关联合同",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 案件",
                "verbose_name_plural": "historical 案件",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCaseNumber",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("number", models.CharField(max_length=128, verbose_name="案号")),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        help_text="如：民事判决书、民事调解书、执行证书等",
                        max_length=128,
                        null=True,
                        verbose_name="文书名称",
                    ),
                ),
                (
                    "document_file",
                    models.TextField(
                        blank=True,
                        help_text="上传PDF格式的裁判文书，用于自动提取执行依据主文",
                        max_length=100,
                        null=True,
                        verbose_name="裁判文书文件",
                    ),
                ),
                (
                    "document_content",
                    models.TextField(
                        blank=True,
                        help_text="从裁判文书自动提取的判决/调解主文内容",
                        null=True,
                        verbose_name="执行依据主文",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="是否已生效")),
                (
                    "execution_cutoff_date",
                    models.DateField(
                        blank=True,
                        help_text="申请执行事项中利息计算截至日期；为空时优先按案件“指定日期”计算，未填写指定日期时按当天计算",
                        null=True,
                        verbose_name="执行事项截止日",
                    ),
                ),
                (
                    "execution_paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="用于按抵扣顺序重算未付款项，默认 0",
                        max_digits=14,
                        verbose_name="已付款金额",
                    ),
                ),
                (
                    "execution_use_deduction_order",
                    models.BooleanField(
                        default=False, help_text="启用后按文书条款中的抵扣顺序处理已付款", verbose_name="启用抵扣顺序"
                    ),
                ),
                (
                    "execution_year_days",
                    models.PositiveSmallIntegerField(
                        choices=[(360, "360天"), (365, "365天"), (0, "按实际天数")],
                        default=360,
                        help_text="利息计算参数：360 / 365 / 按实际天数",
                        verbose_name="年基准天数",
                    ),
                ),
                (
                    "execution_date_inclusion",
                    models.CharField(
                        choices=[
                            ("both", "起止日都计入"),
                            ("start_only", "仅计入起始日"),
                            ("end_only", "仅计入截止日"),
                            ("neither", "起止日都不计入"),
                        ],
                        default="both",
                        help_text="利息计算参数：起止日期是否计入",
                        max_length=16,
                        verbose_name="日期包含方式",
                    ),
                ),
                (
                    "execution_manual_text",
                    models.TextField(
                        blank=True,
                        help_text="有值时模板生成优先使用该文本",
                        null=True,
                        verbose_name="申请执行事项（手工最终文本）",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(blank=True, editable=False, verbose_name="创建时间")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="案件",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 案件案号",
                "verbose_name_plural": "historical 案件案号",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
