# Generated by Django 6.0.4 on 2026-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_add_indexes_and_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselogattachment',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AddField(
            model_name='caselogattachment',
            name='relative_file_path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, verbose_name='相对文件路径'),
        ),
        migrations.AddField(
            model_name='caselogattachment',
            name='storage_root_type',
            field=models.CharField(blank=True, default='media', max_length=32, verbose_name='存储根类型'),
        ),
        migrations.AddField(
            model_name='caselogattachment',
            name='subdir_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='子目录'),
        ),
    ]
