# Generated by Django 6.0.4 on 2026-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_add_inode_and_relative_path'),
        ('cases', '0016_caselog_source_payment_and_more'),
    ]

    operations = [
    ]
