# Generated by Django 6.0.5 on 2026-05-21 06:41

from django.db import migrations, models


SQL = """
-- Backfill any NULLs
UPDATE cases_caselogattachment SET original_filename = '' WHERE original_filename IS NULL;
UPDATE cases_caselogattachment SET relative_file_path = '' WHERE relative_file_path IS NULL;
UPDATE cases_caselogattachment SET storage_root_type = '' WHERE storage_root_type IS NULL;
UPDATE cases_caselogattachment SET subdir_path = '' WHERE subdir_path IS NULL;

-- Add defaults so future INSERTs without these columns work
ALTER TABLE cases_caselogattachment ALTER COLUMN original_filename SET DEFAULT '';
ALTER TABLE cases_caselogattachment ALTER COLUMN relative_file_path SET DEFAULT '';
ALTER TABLE cases_caselogattachment ALTER COLUMN storage_root_type SET DEFAULT '';
ALTER TABLE cases_caselogattachment ALTER COLUMN subdir_path SET DEFAULT '';
"""


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_alter_caselogattachment_file_and_more"),
    ]

    operations = [
        # Columns already exist in the DB (added outside of migrations);
        # only register them in Django's state. SQL handles defaults.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="caselogattachment",
                    name="original_filename",
                    field=models.CharField(blank=True, default="", max_length=500, verbose_name="原始文件名"),
                ),
                migrations.AddField(
                    model_name="caselogattachment",
                    name="relative_file_path",
                    field=models.CharField(blank=True, default="", max_length=1000, verbose_name="相对文件路径"),
                ),
                migrations.AddField(
                    model_name="caselogattachment",
                    name="storage_root_type",
                    field=models.CharField(blank=True, default="", max_length=100, verbose_name="存储根类型"),
                ),
                migrations.AddField(
                    model_name="caselogattachment",
                    name="subdir_path",
                    field=models.CharField(blank=True, default="", max_length=1000, verbose_name="子目录路径"),
                ),
            ],
            database_operations=[
                migrations.RunSQL(SQL, migrations.RunSQL.noop),
            ],
        ),
    ]
