# Generated by Django 6.0.5 on 2026-05-21 06:41

from django.db import migrations, models


SQL = """
DO $$
BEGIN
    -- Only run if columns already exist (e.g. added outside migrations)
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'cases_caselogattachment' AND column_name = 'original_filename'
    ) THEN
        UPDATE cases_caselogattachment SET original_filename = '' WHERE original_filename IS NULL;
        UPDATE cases_caselogattachment SET relative_file_path = '' WHERE relative_file_path IS NULL;
        UPDATE cases_caselogattachment SET storage_root_type = '' WHERE storage_root_type IS NULL;
        UPDATE cases_caselogattachment SET subdir_path = '' WHERE subdir_path IS NULL;

        ALTER TABLE cases_caselogattachment ALTER COLUMN original_filename SET DEFAULT '';
        ALTER TABLE cases_caselogattachment ALTER COLUMN relative_file_path SET DEFAULT '';
        ALTER TABLE cases_caselogattachment ALTER COLUMN storage_root_type SET DEFAULT '';
        ALTER TABLE cases_caselogattachment ALTER COLUMN subdir_path SET DEFAULT '';
    ELSE
        -- Fresh DB: columns don't exist yet, ADD them
        ALTER TABLE cases_caselogattachment ADD COLUMN original_filename varchar(500) NOT NULL DEFAULT '';
        ALTER TABLE cases_caselogattachment ADD COLUMN relative_file_path varchar(1000) NOT NULL DEFAULT '';
        ALTER TABLE cases_caselogattachment ADD COLUMN storage_root_type varchar(100) NOT NULL DEFAULT '';
        ALTER TABLE cases_caselogattachment ADD COLUMN subdir_path varchar(1000) NOT NULL DEFAULT '';
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_alter_caselogattachment_file_and_more"),
    ]

    operations = [
        # Columns already exist in the DB (added outside of migrations);
        # only register them in Django's state. SQL handles defaults.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="caselogattachment",
                    name="original_filename",
                    field=models.CharField(blank=True, default="", max_length=500, verbose_name="原始文件名"),
                ),
                migrations.AddField(
                    model_name="caselogattachment",
                    name="relative_file_path",
                    field=models.CharField(blank=True, default="", max_length=1000, verbose_name="相对文件路径"),
                ),
                migrations.AddField(
                    model_name="caselogattachment",
                    name="storage_root_type",
                    field=models.CharField(blank=True, default="", max_length=100, verbose_name="存储根类型"),
                ),
                migrations.AddField(
                    model_name="caselogattachment",
                    name="subdir_path",
                    field=models.CharField(blank=True, default="", max_length=1000, verbose_name="子目录路径"),
                ),
            ],
            database_operations=[
                migrations.RunSQL(SQL, migrations.RunSQL.noop),
            ],
        ),
    ]
