# Generated by Django 6.0.5 on 2026-05-21 06:52

from pathlib import PurePosixPath

from django.db import migrations


def backfill_original_filename(apps, schema_editor):
    """Set original_filename from the stored file path for existing attachments."""
    CaseLogAttachment = apps.get_model("cases", "CaseLogAttachment")
    updated = 0
    for att in CaseLogAttachment.objects.filter(original_filename=""):
        if att.file:
            att.original_filename = PurePosixPath(str(att.file.name)).name
            att.save(update_fields=["original_filename"])
            updated += 1
    if updated:
        print(f"  Backfilled original_filename for {updated} attachments")


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_caselogattachment_add_file_metadata"),
    ]

    operations = [
        migrations.RunPython(backfill_original_filename, migrations.RunPython.noop),
    ]
