# Generated by Django 6.0.5 on 2026-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_cleanup_legacy_caselogattachment_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselogattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='原始文件名'),
        ),
    ]
