export const PATHS = {
  HOME: '/',
  ABOUT: '/about',
  PRICING: '/pricing',
  TUTORIAL: '/tutorial',
  PORTAL: '/portal/:token',

  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',

  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_INBOX: '/admin/inbox',
  ADMIN_INBOX_DETAIL: '/admin/inbox/:id',
  ADMIN_CASES: '/admin/cases',
  ADMIN_CASE_NEW: '/admin/cases/new',
  ADMIN_CASE_DETAIL: '/admin/cases/:id',
  ADMIN_CASE_EDIT: '/admin/cases/:id/edit',
  ADMIN_LOGS: '/admin/logs',
  ADMIN_LOG_DETAIL: '/admin/logs/:id',
  ADMIN_LOG_NEW: '/admin/logs/:id/new',
  ADMIN_LOG_EDIT: '/admin/logs/:caseId/:logId/edit',
  ADMIN_CONTRACTS: '/admin/contracts',
  ADMIN_CONTRACT_NEW: '/admin/contracts/new',
  ADMIN_CONTRACT_DETAIL: '/admin/contracts/:id',
  ADMIN_CONTRACT_EDIT: '/admin/contracts/:id/edit',
  ADMIN_CLIENTS: '/admin/clients',
  ADMIN_CLIENT_NEW: '/admin/clients/new',
  ADMIN_CLIENT_DETAIL: '/admin/clients/:id',
  ADMIN_CLIENT_EDIT: '/admin/clients/:id/edit',
  ADMIN_DOCUMENTS: '/admin/documents',
  ADMIN_REMINDERS: '/admin/reminders',

  ADMIN_ORGANIZATION: '/admin/organization',
  ADMIN_LAWFIRMS: '/admin/organization/lawfirms',
  ADMIN_LAWFIRM_NEW: '/admin/organization/lawfirms/new',
  ADMIN_LAWFIRM_DETAIL: '/admin/organization/lawfirms/:id',
  ADMIN_LAWFIRM_EDIT: '/admin/organization/lawfirms/:id/edit',
  ADMIN_LAWYERS: '/admin/organization/lawyers',
  ADMIN_LAWYER_NEW: '/admin/organization/lawyers/new',
  ADMIN_LAWYER_DETAIL: '/admin/organization/lawyers/:id',
  ADMIN_LAWYER_EDIT: '/admin/organization/lawyers/:id/edit',
  ADMIN_TEAMS: '/admin/organization/teams',
  ADMIN_CREDENTIALS: '/admin/organization/credentials',

  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_SETTINGS_USER: '/admin/settings/user',
  ADMIN_SETTINGS_SYSTEM: '/admin/settings/system',

  ADMIN_AUTOMATION: '/admin/automation',
  ADMIN_AUTOMATION_QUOTES: '/admin/automation/preservation-quotes',
  ADMIN_AUTOMATION_QUOTE_DETAIL: '/admin/automation/preservation-quotes/:id',
  ADMIN_AUTOMATION_RECOGNITION: '/admin/automation/document-recognition',
  ADMIN_AUTOMATION_RECOGNITION_DETAIL: '/admin/automation/document-recognition/:id',

  GITHUB: 'https://github.com/huangsong/fachuanai',
} as const

export const generatePath = {
  portal: (token: string) => `/portal/${token}`,
  inboxDetail: (id: string | number) => `/admin/inbox/${id}`,
  caseDetail: (id: string | number) => `/admin/cases/${id}`,
  caseEdit: (id: string | number) => `/admin/cases/${id}/edit`,
  caseLogDetail: (id: string | number) => `/admin/logs/${id}`,
  caseLogNew: (id: string | number) => `/admin/logs/${id}/new`,
  caseLogEdit: (caseId: string | number, logId: string | number) => `/admin/logs/${caseId}/${logId}/edit`,
  contractDetail: (id: string | number) => `/admin/contracts/${id}`,
  contractEdit: (id: string | number) => `/admin/contracts/${id}/edit`,
  clientDetail: (id: string | number) => `/admin/clients/${id}`,
  clientEdit: (id: string | number) => `/admin/clients/${id}/edit`,
  lawFirmDetail: (id: string | number) => `/admin/organization/lawfirms/${id}`,
  lawFirmEdit: (id: string | number) => `/admin/organization/lawfirms/${id}/edit`,
  lawyerDetail: (id: string | number) => `/admin/organization/lawyers/${id}`,
  lawyerEdit: (id: string | number) => `/admin/organization/lawyers/${id}/edit`,
  quoteDetail: (id: string | number) => `/admin/automation/preservation-quotes/${id}`,
  recognitionDetail: (id: string | number) => `/admin/automation/document-recognition/${id}`,
} as const
