# Generated by Django 6.0.3 on 2026-03-31 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("legal_research", "0008_case_download"),
        ("organization", "0002_remove_is_preferred"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_summary", models.TextField(verbose_name="案情简述")),
                ("keyword", models.CharField(blank=True, max_length=255, verbose_name="检索关键词")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("researching", "检索中"),
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("partial", "部分完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0, verbose_name="进度")),
                ("message", models.CharField(blank=True, max_length=255, verbose_name="状态说明")),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                ("llm_model", models.CharField(blank=True, max_length=128, verbose_name="LLM模型")),
                ("html_content", models.TextField(blank=True, verbose_name="HTML方案")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, max_length=255, null=True, upload_to="legal_solution/pdf/", verbose_name="PDF文件"
                    ),
                ),
                ("q_task_id", models.CharField(blank=True, max_length=64, verbose_name="队列任务ID")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solution_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solution_tasks",
                        to="organization.accountcredential",
                        verbose_name="站点账号",
                    ),
                ),
                (
                    "research_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solution_tasks",
                        to="legal_research.legalresearchtask",
                        verbose_name="案例检索任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "法律服务方案",
                "verbose_name_plural": "法律服务方案",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SolutionSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("case_analysis", "案情分析"),
                            ("legal_relation", "法律关系认定"),
                            ("dispute_focus", "争议焦点"),
                            ("similar_cases", "类案参考"),
                            ("litigation_strategy", "诉讼策略建议"),
                            ("risk_assessment", "风险评估"),
                            ("cost_estimate", "费用预估"),
                        ],
                        max_length=32,
                        verbose_name="段落类型",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("title", models.CharField(max_length=128, verbose_name="标题")),
                ("content", models.TextField(blank=True, verbose_name="内容(markdown)")),
                ("html_content", models.TextField(blank=True, verbose_name="HTML内容")),
                ("prompt_used", models.TextField(blank=True, verbose_name="使用的Prompt")),
                ("user_feedback", models.TextField(blank=True, verbose_name="用户调整意见")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="版本号")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待生成"),
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="扩展信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="legal_solution.solutiontask",
                        verbose_name="方案任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "方案段落",
                "verbose_name_plural": "方案段落",
                "ordering": ["order"],
                "unique_together": {("task", "section_type")},
            },
        ),
    ]
