# Generated by Django 6.0.2 on 2026-02-28 17:13

import apps.chat_records.models.export_task
import apps.chat_records.models.recording
import apps.chat_records.models.screenshot
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRecordProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_record_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "梳理聊天记录",
                "verbose_name_plural": "梳理聊天记录",
            },
        ),
        migrations.CreateModel(
            name="ChatRecordExportTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "export_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "Word")], max_length=16, verbose_name="导出类型"
                    ),
                ),
                ("layout", models.JSONField(blank=True, default=dict, verbose_name="版式配置")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("running", "处理中"), ("success", "成功"), ("failed", "失败")],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0, verbose_name="进度百分比")),
                ("current", models.PositiveIntegerField(default=0, verbose_name="当前项")),
                ("total", models.PositiveIntegerField(default=0, verbose_name="总项")),
                ("message", models.CharField(blank=True, max_length=255, verbose_name="进度信息")),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "output_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.chat_records.models.export_task._export_upload_to,
                        verbose_name="导出文件",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_tasks",
                        to="chat_records.chatrecordproject",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天记录导出任务",
                "verbose_name_plural": "聊天记录导出任务",
            },
        ),
        migrations.CreateModel(
            name="ChatRecordRecording",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "video",
                    models.FileField(
                        upload_to=apps.chat_records.models.recording._recording_upload_to, verbose_name="录屏文件"
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=255, verbose_name="原始文件名")),
                ("size_bytes", models.BigIntegerField(default=0, verbose_name="文件大小(字节)")),
                ("duration_seconds", models.FloatField(blank=True, null=True, verbose_name="时长(秒)")),
                (
                    "extract_status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("running", "处理中"), ("success", "成功"), ("failed", "失败")],
                        default="pending",
                        max_length=16,
                        verbose_name="抽帧状态",
                    ),
                ),
                (
                    "extract_strategy",
                    models.CharField(
                        choices=[
                            ("interval", "固定间隔"),
                            ("scene", "画面变化优先"),
                            ("smart", "智能去重"),
                            ("keyframe", "关键帧(I帧)"),
                            ("ocr", "OCR 文本变化优先"),
                        ],
                        default="interval",
                        max_length=16,
                        verbose_name="抽帧策略",
                    ),
                ),
                ("extract_dedup_threshold", models.IntegerField(blank=True, null=True, verbose_name="抽帧去重阈值")),
                (
                    "extract_ocr_similarity_threshold",
                    models.FloatField(blank=True, null=True, verbose_name="OCR 相似度阈值"),
                ),
                (
                    "extract_ocr_min_new_chars",
                    models.IntegerField(blank=True, null=True, verbose_name="OCR 新增字符阈值"),
                ),
                ("extract_cancel_requested", models.BooleanField(default=False, verbose_name="请求取消抽帧")),
                ("extract_progress", models.PositiveIntegerField(default=0, verbose_name="抽帧进度百分比")),
                ("extract_current", models.PositiveIntegerField(default=0, verbose_name="抽帧当前项")),
                ("extract_total", models.PositiveIntegerField(default=0, verbose_name="抽帧总项")),
                ("extract_message", models.CharField(blank=True, max_length=255, verbose_name="抽帧进度信息")),
                ("extract_error", models.TextField(blank=True, verbose_name="抽帧错误信息")),
                ("extract_started_at", models.DateTimeField(blank=True, null=True, verbose_name="抽帧开始时间")),
                ("extract_finished_at", models.DateTimeField(blank=True, null=True, verbose_name="抽帧完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="chat_records.chatrecordproject",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天记录录屏",
                "verbose_name_plural": "聊天记录录屏",
            },
        ),
        migrations.CreateModel(
            name="ChatRecordScreenshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.chat_records.models.screenshot._screenshot_upload_to, verbose_name="截图"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0, verbose_name="顺序")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="标题")),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("capture_time_seconds", models.FloatField(blank=True, null=True, verbose_name="截图时间点(秒)")),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64, verbose_name="内容哈希")),
                ("dhash", models.CharField(blank=True, db_index=True, max_length=16, verbose_name="感知哈希")),
                ("frame_score", models.FloatField(blank=True, null=True, verbose_name="帧评分")),
                (
                    "source",
                    models.CharField(
                        choices=[("unknown", "未知"), ("extract", "视频抽帧"), ("upload", "手动上传")],
                        default="unknown",
                        max_length=16,
                        verbose_name="来源",
                    ),
                ),
                ("is_filtered", models.BooleanField(default=False, verbose_name="已过滤")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="chat_records.chatrecordproject",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天记录截图",
                "verbose_name_plural": "聊天记录截图",
                "ordering": ["ordering", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatrecordproject",
            index=models.Index(fields=["-created_at"], name="chat_record_created_e3135d_idx"),
        ),
        migrations.AddIndex(
            model_name="chatrecordproject",
            index=models.Index(fields=["created_by"], name="chat_record_created_2cdaba_idx"),
        ),
        migrations.AddIndex(
            model_name="chatrecordexporttask",
            index=models.Index(fields=["project", "-created_at"], name="chat_record_project_514dd4_idx"),
        ),
        migrations.AddIndex(
            model_name="chatrecordexporttask",
            index=models.Index(fields=["status", "-created_at"], name="chat_record_status_46ee60_idx"),
        ),
        migrations.AddIndex(
            model_name="chatrecordrecording",
            index=models.Index(fields=["project", "-created_at"], name="chat_record_project_03452e_idx"),
        ),
        migrations.AddIndex(
            model_name="chatrecordrecording",
            index=models.Index(fields=["extract_status", "-created_at"], name="chat_record_extract_ec953d_idx"),
        ),
        migrations.AddIndex(
            model_name="chatrecordscreenshot",
            index=models.Index(fields=["project", "ordering"], name="chat_record_project_8855d4_idx"),
        ),
        migrations.AddIndex(
            model_name="chatrecordscreenshot",
            index=models.Index(fields=["project", "dhash"], name="chat_record_project_9ea8f6_idx"),
        ),
        migrations.AddIndex(
            model_name="chatrecordscreenshot",
            index=models.Index(fields=["project", "-created_at"], name="chat_record_project_f2e392_idx"),
        ),
    ]
