"""Module for reference data protocols."""

from typing import Any, Protocol


class ICauseCourtQueryService(Protocol):
    def has_active_causes_internal(self) -> bool: ...

    def has_active_courts_internal(self) -> bool: ...

    def get_cause_id_by_name_internal(self, name: str) -> int | None: ...

    def get_cause_ancestor_codes_internal(self, cause_id: int) -> list[str]: ...

    def get_cause_ancestor_names_internal(self, cause_id: int) -> list[str]: ...

    def search_causes_internal(self, query: str, case_type: str | None, limit: int) -> list[dict[str, Any]]: ...

    def search_courts_internal(self, query: str, limit: int) -> list[dict[str, Any]]: ...

    def list_causes_by_parent_internal(self, parent_id: int | None = None) -> list[dict[str, Any]]: ...

    def get_legal_statuses_for_case_type(self, case_type: str | None) -> list[tuple[Any, ...]]: ...

    def get_stage_label(self, value: str) -> str: ...

    def get_legal_status_label(self, value: str) -> str: ...

    def is_stage_valid_for_case_type(self, stage: str, case_type: str | None) -> bool: ...

    def is_legal_status_valid_for_case_type(self, status: str, case_type: str | None) -> bool: ...

    def get_compatible_legal_statuses(
        self, existing_statuses: list[str], case_type: str | None = None
    ) -> list[tuple[Any, ...]]: ...

    def is_legal_status_compatible(self, new_status: str, existing_statuses: list[str]) -> bool: ...

    def get_stages_for_case_type_internal(self, case_type: str | None) -> list[tuple[Any, ...]]: ...

    def get_legal_statuses_for_case_type_internal(self, case_type: str | None) -> list[tuple[Any, ...]]: ...

    def get_cause_by_id_internal(self, cause_id: int) -> dict[str, Any] | None:
        """
        根据 ID 获取案由信息

        Args:
            cause_id: 案由 ID

        Returns:
            案由信息字典(包含 id, name, code, case_type),不存在返回 None
        """
        ...
