from __future__ import annotations

import json
from html import escape


class AnimationHtmlComposerService:
    def compose(
        self,
        *,
        title: str,
        viz_type: str,
        render_payload: dict[str, object],
        fragment_payload: dict[str, object],
    ) -> str:
        safe_title = escape(title or "故事可视化")
        render_json = json.dumps(render_payload, ensure_ascii=False)
        fragment_json = json.dumps(fragment_payload, ensure_ascii=False)

        return f"""<!doctype html>
<html lang=\"zh-CN\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>{safe_title}</title>
  <style>
    body{{margin:0;padding:0;background:#0f172a;color:#e2e8f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;}}
    .wrap{{padding:20px;max-width:1100px;margin:0 auto;}}
    .card{{background:rgba(15,23,42,.66);border:1px solid rgba(148,163,184,.25);border-radius:16px;padding:16px;backdrop-filter: blur(6px);}}
    h1{{font-size:20px;margin:0 0 6px;}}
    .meta{{font-size:12px;color:#94a3b8;margin-bottom:14px;}}
    .node{{display:inline-block;padding:8px 10px;border-radius:10px;background:rgba(56,189,248,.18);margin:6px;}}
    .edge{{font-size:12px;color:#cbd5e1;margin:4px 0;}}
  </style>
</head>
<body>
  <div class=\"wrap\">
    <div class=\"card\">
      <h1>{safe_title}</h1>
      <div class=\"meta\">viz_type: {escape(viz_type)} | generated by story_viz</div>
      <div id=\"viz-root\"></div>
    </div>
  </div>
  <script>
    const payload = {render_json};
    const fragments = {fragment_json};
    const root = document.getElementById('viz-root');
    if (payload.viz_type === 'relationship') {{
      const nodes = payload.nodes || [];
      const edges = payload.edges || [];
      root.innerHTML = `
        <div><strong>人物节点</strong></div>
        <div>${{nodes.map(n => `<span class=\"node\">${{n.label || n.id}}</span>`).join('')}}</div>
        <div style=\"margin-top:10px\"><strong>关系</strong></div>
        <div>${{edges.map(e => `<div class=\"edge\">${{e.source}} → ${{e.target}} (${{e.relation || ''}})</div>`).join('')}}</div>
      `;
    }} else {{
      const nodes = payload.nodes || [];
      root.innerHTML = `
        <div><strong>时间线节点</strong></div>
        <div>${{nodes.map(n => `<span class=\"node\">${{n.time || ''}} ${{n.label || ''}}</span>`).join('')}}</div>
      `;
    }}
  </script>
</body>
</html>
"""
