# Generated by Django 6.0.2 on 2026-04-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_initial"),
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="cases.case",
                verbose_name="案件",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="reminder",
            name="reminders_reminder_bind_exactly_one",
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.CheckConstraint(
                condition=(models.Q(("contract__isnull", True)) | models.Q(("case__isnull", True)))
                & (models.Q(("contract__isnull", True)) | models.Q(("case_log__isnull", True)))
                & (models.Q(("case__isnull", True)) | models.Q(("case_log__isnull", True))),
                name="reminders_reminder_bind_at_most_one",
            ),
        ),
    ]
