# Generated by Django 6.0.4 on 2026-04-25 07:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_historical_records"),
        ("contracts", "0024_historical_records"),
        ("reminders", "0002_reminder_case_optional_binding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReminder",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("hearing", "开庭"),
                            ("asset_preservation_expires", "财产保全到期日"),
                            ("evidence_deadline", "举证到期日"),
                            ("appeal_deadline", "上诉期到期日"),
                            ("statute_limitations", "诉讼时效到期日"),
                            ("payment_deadline", "缴费期限"),
                            ("submission_deadline", "补正/材料提交期限"),
                            ("other", "其他"),
                        ],
                        max_length=64,
                        verbose_name="类型",
                    ),
                ),
                ("content", models.CharField(max_length=255, verbose_name="提醒事项")),
                ("due_at", models.DateTimeField(verbose_name="到期时间")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="扩展数据")),
                ("created_at", models.DateTimeField(blank=True, editable=False, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(blank=True, editable=False, verbose_name="更新时间")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="案件",
                    ),
                ),
                (
                    "case_log",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.caselog",
                        verbose_name="案件日志",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 重要日期提醒",
                "verbose_name_plural": "historical 重要日期提醒",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
