# Generated by Django 6.0.4 on 2026-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocConvertTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '传统文书转换',
                'verbose_name_plural': '传统文书转换',
                'managed': False,
            },
        ),
    ]
