# Generated by Django 6.0.4 on 2026-04-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc_convert", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docconverttool",
            options={"managed": False, "verbose_name": "要素式转换", "verbose_name_plural": "要素式转换"},
        ),
    ]
