"""文件模板默认数据"""

DEFAULT_DOCUMENT_TEMPLATES = [
    {
        "name": "补充协议",
        "template_type": "contract",
        "contract_sub_type": "supplementary_agreement",
        "case_sub_type": None,
        "file_path": "1-合同模板/补充协议.docx",
        "contract_types": ["all"],
        "case_types": [],
        "case_stages": [],
        "legal_statuses": [],
        "legal_status_match_mode": "any",
        "is_active": True,
    },
    {
        "name": "所函",
        "template_type": "case",
        "contract_sub_type": None,
        "case_sub_type": "power_of_attorney_materials",
        "file_path": "2-案件材料/4-通用材料/1-授权委托材料/所函.docx",
        "contract_types": [],
        "case_types": ["all"],
        "case_stages": ["all"],
        "legal_statuses": [],
        "legal_status_match_mode": "any",
        "is_active": True,
    },
    {
        "name": "授权委托书",
        "template_type": "case",
        "contract_sub_type": None,
        "case_sub_type": "power_of_attorney_materials",
        "file_path": "2-案件材料/4-通用材料/1-授权委托材料/授权委托书.docx",
        "contract_types": [],
        "case_types": ["all"],
        "case_stages": ["all"],
        "legal_statuses": [],
        "legal_status_match_mode": "any",
        "is_active": True,
    },
    {
        "name": "法定代表人身份证明书",
        "template_type": "case",
        "contract_sub_type": None,
        "case_sub_type": "power_of_attorney_materials",
        "file_path": "2-案件材料/4-通用材料/1-授权委托材料/法定代表人身份证明书.docx",
        "contract_types": [],
        "case_types": ["all"],
        "case_stages": ["all"],
        "legal_statuses": [],
        "legal_status_match_mode": "any",
        "is_active": True,
    },
    {
        "name": "民商事合同",
        "template_type": "contract",
        "contract_sub_type": "contract",
        "case_sub_type": None,
        "file_path": "1-合同模板/民商事代理合同.docx",
        "contract_types": ["civil"],
        "case_types": [],
        "case_stages": [],
        "legal_statuses": [],
        "legal_status_match_mode": "any",
        "is_active": True,
    },
]
