# Generated by Django 6.0.4 on 2026-04-16 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryAnimation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_title", models.CharField(max_length=255, verbose_name="文书标题")),
                ("source_text", models.TextField(verbose_name="文书原文")),
                (
                    "viz_type",
                    models.CharField(
                        choices=[("timeline", "时间线"), ("relationship", "人物关系图")],
                        default="timeline",
                        max_length=32,
                        verbose_name="可视化类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("queued", "已入队"),
                            ("extracting_facts", "提取事实"),
                            ("directing_script", "编排脚本"),
                            ("rendering_layout", "渲染布局"),
                            ("generating_fragments", "生成视觉片段"),
                            ("composing_html", "组装HTML"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="queued",
                        max_length=48,
                        verbose_name="当前阶段",
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0, verbose_name="进度")),
                ("task_id", models.CharField(blank=True, default="", max_length=64, verbose_name="任务ID")),
                ("cancel_requested", models.BooleanField(default=False, verbose_name="请求取消")),
                ("source_hash", models.CharField(blank=True, default="", max_length=64, verbose_name="原文哈希")),
                ("facts_payload", models.JSONField(blank=True, default=dict, verbose_name="事实结构化结果")),
                ("script_payload", models.JSONField(blank=True, default=dict, verbose_name="动画脚本结果")),
                ("render_payload", models.JSONField(blank=True, default=dict, verbose_name="渲染骨架结果")),
                ("animation_html", models.TextField(blank=True, default="", verbose_name="动画HTML")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="story_animations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "故事可视化",
                "verbose_name_plural": "故事可视化",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="story_viz_s_status_662258_idx"),
                    models.Index(fields=["viz_type", "-created_at"], name="story_viz_s_viz_typ_e8e2b0_idx"),
                    models.Index(fields=["source_hash"], name="story_viz_s_source__30758f_idx"),
                ],
            },
        ),
    ]
