# Generated by Django 6.0.4 on 2026-05-06 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbenchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('llm_model', models.CharField(blank=True, default='', help_text='使用的 LLM 模型 ID', max_length=255, verbose_name='LLM 模型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workbench_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作台会话',
                'verbose_name_plural': '工作台会话',
                'db_table': 'workbench_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkbenchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', '系统'), ('user', '用户'), ('assistant', '助手'), ('tool', '工具')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('llm_model', models.CharField(blank=True, default='', help_text='该消息使用的 LLM 模型 ID', max_length=255, verbose_name='LLM 模型')),
                ('tool_call_id', models.CharField(blank=True, default='', help_text='工具调用的唯一标识', max_length=255, verbose_name='工具调用 ID')),
                ('tool_name', models.CharField(blank=True, default='', help_text='工具名称（如果是工具调用）', max_length=255, verbose_name='工具名称')),
                ('tool_input', models.JSONField(blank=True, default=dict, help_text='工具输入参数', verbose_name='工具输入')),
                ('tool_output', models.JSONField(blank=True, default=dict, help_text='工具输出结果', verbose_name='工具输出')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workbench.workbenchsession')),
            ],
            options={
                'verbose_name': '工作台消息',
                'verbose_name_plural': '工作台消息',
                'db_table': 'workbench_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workbenchsession',
            index=models.Index(fields=['user', '-updated_at'], name='workbench_s_user_id_727f82_idx'),
        ),
        migrations.AddIndex(
            model_name='workbenchsession',
            index=models.Index(fields=['status'], name='workbench_s_status_8e0107_idx'),
        ),
        migrations.AddIndex(
            model_name='workbenchmessage',
            index=models.Index(fields=['session', 'created_at'], name='workbench_m_session_0e4cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='workbenchmessage',
            index=models.Index(fields=['role'], name='workbench_m_role_cfe729_idx'),
        ),
    ]
