# Generated by Django 6.0.2 on 2026-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemconfig",
            name="category",
            field=models.CharField(
                choices=[
                    ("feishu", "飞书配置"),
                    ("dingtalk", "钉钉配置"),
                    ("wechat_work", "企业微信配置"),
                    ("court_sms", "法院短信配置"),
                    ("ai", "AI 服务配置"),
                    ("llm", "LLM 大模型配置"),
                    ("enterprise_data", "企业数据配置"),
                    ("scraper", "爬虫配置"),
                    ("general", "通用配置"),
                ],
                default="general",
                help_text="配置项所属分类",
                max_length=50,
                verbose_name="分类",
            ),
        ),
    ]
