# Generated by Django 6.0.4 on 2026-04-24 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_systemconfig_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tool_url", models.CharField(max_length=255, verbose_name="工具 URL")),
                ("tool_name", models.CharField(blank=True, default="", max_length=100, verbose_name="工具名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="收藏时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "工具收藏",
                "verbose_name_plural": "工具收藏",
                "ordering": ["-created_at"],
                "unique_together": {("user", "tool_url")},
            },
        ),
    ]
