"""
跨模块 DTO 兼容出口
"""

from apps.core.dto import (
    AccountCredentialDTO,
    CaseDTO,
    CasePartyDTO,
    CaseSearchResultDTO,
    CaseTemplateBindingDTO,
    ClientDTO,
    ClientIdentityDocDTO,
    ContractDTO,
    ConversationHistoryDTO,
    CourtPleadingSignalsDTO,
    DocumentTemplateDTO,
    EvidenceItemDigestDTO,
    GenerationTaskDTO,
    LawFirmDTO,
    LawyerDTO,
    LoginAttemptResult,
    PartyRoleDTO,
    PropertyClueDTO,
    ReminderDTO,
    ReminderTypeDTO,
    SupplementaryAgreementDTO,
    TokenAcquisitionResult,
)

__all__: list[str] = [
    "AccountCredentialDTO",
    "CaseDTO",
    "CasePartyDTO",
    "CaseSearchResultDTO",
    "CaseTemplateBindingDTO",
    "ClientDTO",
    "ClientIdentityDocDTO",
    "ContractDTO",
    "ConversationHistoryDTO",
    "CourtPleadingSignalsDTO",
    "DocumentTemplateDTO",
    "EvidenceItemDigestDTO",
    "GenerationTaskDTO",
    "LawFirmDTO",
    "LawyerDTO",
    "LoginAttemptResult",
    "PartyRoleDTO",
    "PropertyClueDTO",
    "ReminderDTO",
    "ReminderTypeDTO",
    "SupplementaryAgreementDTO",
    "TokenAcquisitionResult",
]
