# Generated by Django 6.0.2 on 2026-02-28 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("page_start", models.IntegerField(blank=True, null=True)),
                ("page_end", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, default="")),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("extraction_method", models.CharField(blank=True, default="", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evidence_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chunks",
                        to="documents.evidenceitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "证据片段",
                "verbose_name_plural": "证据片段",
                "indexes": [models.Index(fields=["evidence_item"], name="litigation__evidenc_13942d_idx")],
            },
        ),
        migrations.CreateModel(
            name="LitigationSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="唯一标识一次文书生成会话",
                        unique=True,
                        verbose_name="会话ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("complaint", "起诉状"),
                            ("defense", "答辩状"),
                            ("counterclaim", "反诉状"),
                            ("counterclaim_defense", "反诉答辩状"),
                        ],
                        help_text="起诉状、答辩状、反诉状等",
                        max_length=50,
                        verbose_name="文书类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "进行中"), ("completed", "已完成"), ("cancelled", "已取消")],
                        default="active",
                        max_length=20,
                        verbose_name="会话状态",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="存储诉讼目标、证据清单ID、token消耗等信息", verbose_name="会话元数据"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litigation_sessions",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="litigation_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI文书生成会话",
                "verbose_name_plural": "AI文书生成会话",
                "db_table": "documents_litigationsession",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["session_id"], name="documents_l_session_80e25a_idx"),
                    models.Index(fields=["case", "-created_at"], name="documents_l_case_id_89c48b_idx"),
                    models.Index(fields=["user", "-created_at"], name="documents_l_user_id_76982c_idx"),
                    models.Index(fields=["status"], name="documents_l_status_250626_idx"),
                    models.Index(fields=["document_type"], name="documents_l_documen_5ea5d2_idx"),
                ],
            },
        ),
    ]
