# Generated by Django 6.0.2 on 2026-02-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("litigation_ai", "0002_add_session_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="litigationsession",
            new_name="documents_l_session_07fff0_idx",
            old_name="documents_li_session_8e1f3a_idx",
        ),
    ]
