# Generated by Django 6.0.3 on 2026-03-31 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_remove_is_preferred'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('imap', 'IMAP 邮箱'), ('court_inbox', '一张网收件箱')], default='imap', max_length=32, verbose_name='来源类型')),
                ('display_name', models.CharField(max_length=128, verbose_name='显示名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('poll_interval_minutes', models.PositiveIntegerField(default=30, verbose_name='轮询间隔（分钟）')),
                ('sync_since', models.DateTimeField(help_text='只拉取此时间之后的消息', verbose_name='同步起始时间')),
                ('last_synced_uid', models.PositiveIntegerField(blank=True, null=True, verbose_name='最后同步 UID')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('last_sync_status', models.CharField(choices=[('pending', '待同步'), ('success', '同步成功'), ('failed', '同步失败')], default='pending', max_length=16, verbose_name='同步状态')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='同步错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sources', to='organization.accountcredential', verbose_name='账号凭证')),
            ],
            options={
                'verbose_name': '消息来源',
                'verbose_name_plural': '消息来源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=512, verbose_name='原始消息 ID')),
                ('subject', models.CharField(blank=True, max_length=512, verbose_name='主题')),
                ('sender', models.CharField(blank=True, max_length=512, verbose_name='发件人')),
                ('received_at', models.DateTimeField(verbose_name='接收时间')),
                ('body_text', models.TextField(blank=True, verbose_name='正文（纯文本）')),
                ('body_html', models.TextField(blank=True, verbose_name='正文（HTML）')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='有附件')),
                ('attachments_meta', models.JSONField(default=list, verbose_name='附件元信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message_hub.messagesource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '收件箱消息',
                'verbose_name_plural': '收件箱消息',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source', '-received_at'], name='message_hub_source__dd97dd_idx'), models.Index(fields=['is_read', '-received_at'], name='message_hub_is_read_3a6bde_idx')],
                'unique_together': {('source', 'message_id')},
            },
        ),
    ]
