# Generated by Django 6.0.3 on 2026-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesource',
            name='imap_host',
            field=models.CharField(blank=True, help_text='留空则从凭证 URL 自动推断，如 mail.jtn.com', max_length=255, verbose_name='IMAP 主机'),
        ),
    ]
