# Generated by Django 6.0.3 on 2026-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0002_messagesource_imap_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesource',
            name='imap_account',
            field=models.CharField(blank=True, help_text='留空则使用凭证账号，如需覆盖填写完整邮箱地址', max_length=255, verbose_name='IMAP 账号'),
        ),
    ]
