# Generated by Django 6.0.3 on 2026-03-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0003_messagesource_imap_account'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inboxmessage',
            name='message_hub_is_read_3a6bde_idx',
        ),
        migrations.RemoveField(
            model_name='inboxmessage',
            name='is_read',
        ),
    ]
