# Generated by Django 6.0.3 on 2026-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_hub", "0004_remove_inboxmessage_message_hub_is_read_3a6bde_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesource",
            name="sender_blacklist",
            field=models.TextField(
                blank=True, help_text="每行一个邮箱或名称，留空则不排除", verbose_name="不同步这些发件人"
            ),
        ),
        migrations.AddField(
            model_name="messagesource",
            name="sender_whitelist",
            field=models.TextField(
                blank=True, help_text="每行一个邮箱或名称，留空则不限制", verbose_name="只同步这些发件人"
            ),
        ),
    ]
