# Generated by Django 6.0.4 on 2026-04-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_hub", "0005_add_sender_whitelist_blacklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagesource",
            name="source_type",
            field=models.CharField(
                choices=[("imap", "IMAP 邮箱"), ("court_inbox", "一张网收件箱"), ("court_schedule", "一张网庭审日程")],
                default="imap",
                max_length=32,
                verbose_name="来源类型",
            ),
        ),
    ]
