# Generated by Django 6.0.3 on 2026-04-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("express_query", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpressQueryTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Express Query", max_length=64)),
            ],
            options={
                "verbose_name": "快递查询上传",
                "verbose_name_plural": "快递查询上传",
                "managed": False,
            },
        ),
    ]
