# Generated by Django 6.0.3 on 2026-04-04 10:35

import apps.express_query.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("express_query", "0002_expressquerytool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expressquerytask",
            name="waybill_image",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.express_query.models._waybill_upload_to, verbose_name="邮单页面"
            ),
        ),
    ]
