# Generated by Django 6.0.4 on 2026-04-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("express_query", "0003_allow_waybill_image_blank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expressquerytool",
            options={"managed": False, "verbose_name": "查询EMS/顺丰", "verbose_name_plural": "查询EMS/顺丰"},
        ),
    ]
