# Generated by Django 6.0.2 on 2026-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LPRRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "effective_date",
                    models.DateField(help_text="LPR利率生效日期，通常为每月20日", unique=True, verbose_name="生效日期"),
                ),
                (
                    "rate_1y",
                    models.DecimalField(
                        decimal_places=2, help_text="一年期贷款市场报价利率", max_digits=5, verbose_name="一年期LPR(%)"
                    ),
                ),
                (
                    "rate_5y",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="五年期以上贷款市场报价利率",
                        max_digits=5,
                        verbose_name="五年期LPR(%)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="数据来源说明，如：中国人民银行官网",
                        max_length=255,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "is_auto_synced",
                    models.BooleanField(default=False, help_text="是否通过系统自动同步获取", verbose_name="自动同步"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "LPR利率",
                "verbose_name_plural": "LPR利率",
                "ordering": ["-effective_date"],
                "indexes": [models.Index(fields=["effective_date"], name="finance_lpr_eff_date_idx")],
            },
        ),
    ]
