# Generated by Django 6.0.2 on 2026-02-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_initial"),
        ("documents", "0003_evidenceitem_cross_examination_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="分组名称")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_groups",
                        to="cases.case",
                        verbose_name="案件",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="documents.evidenceitem", verbose_name="关联证据"
                    ),
                ),
            ],
            options={
                "verbose_name": "证据分组",
                "verbose_name_plural": "证据分组",
                "ordering": ["sort_order", "created_at"],
                "indexes": [models.Index(fields=["case", "sort_order"], name="evidence_ev_case_id_2921c9_idx")],
            },
        ),
        migrations.CreateModel(
            name="HearingNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="笔记内容")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录时间")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearing_notes",
                        to="cases.case",
                        verbose_name="案件",
                    ),
                ),
                (
                    "evidence_items",
                    models.ManyToManyField(
                        blank=True, related_name="hearing_notes", to="documents.evidenceitem", verbose_name="关联证据"
                    ),
                ),
            ],
            options={
                "verbose_name": "庭审笔记",
                "verbose_name_plural": "庭审笔记",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["case", "-created_at"], name="evidence_he_case_id_fa3d32_idx")],
            },
        ),
    ]
