# Generated by Django 6.0.2 on 2026-02-28 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_initial"),
        ("contracts", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationScript",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="脚本名称")),
                ("steps_template", models.JSONField(verbose_name="参数化步骤模板")),
                ("script_content", models.TextField(blank=True, verbose_name="生成的 Playwright 脚本")),
                (
                    "parameter_schema",
                    models.JSONField(
                        blank=True, default=dict, help_text="脚本所需参数的名称和描述", verbose_name="参数定义"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "自动化脚本",
                "verbose_name_plural": "自动化脚本",
            },
        ),
        migrations.CreateModel(
            name="OAConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("oa_system_name", models.CharField(max_length=128, verbose_name="OA系统名称")),
                ("base_url", models.URLField(verbose_name="OA系统基础URL")),
                ("login_path", models.CharField(default="/login", max_length=256, verbose_name="登录页路径")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "field_mapping",
                    models.JSONField(
                        blank=True, default=dict, help_text="本系统字段到OA表单字段的映射", verbose_name="字段映射规则"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "law_firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oa_configs",
                        to="organization.lawfirm",
                        verbose_name="律所",
                    ),
                ),
            ],
            options={
                "verbose_name": "OA系统配置",
                "verbose_name_plural": "OA系统配置",
            },
        ),
        migrations.CreateModel(
            name="FilingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开始"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("steps_data", models.JSONField(blank=True, default=list, verbose_name="操作步骤记录")),
                ("last_screenshot", models.BinaryField(blank=True, null=True, verbose_name="最新截图")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "automation_script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="oa_filing.automationscript",
                        verbose_name="使用的自动化脚本",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_sessions",
                        to="cases.case",
                        verbose_name="案件",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_sessions",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filing_sessions",
                        to="organization.accountcredential",
                        verbose_name="登录凭证",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起用户",
                    ),
                ),
                (
                    "oa_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_sessions",
                        to="oa_filing.oaconfig",
                        verbose_name="OA配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "立案会话",
                "verbose_name_plural": "立案会话",
            },
        ),
        migrations.AddField(
            model_name="automationscript",
            name="oa_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to="oa_filing.oaconfig",
                verbose_name="关联OA配置",
            ),
        ),
        migrations.AddIndex(
            model_name="oaconfig",
            index=models.Index(fields=["law_firm", "is_enabled"], name="oa_filing_o_law_fir_5d5654_idx"),
        ),
        migrations.AddIndex(
            model_name="filingsession",
            index=models.Index(fields=["contract", "-created_at"], name="oa_filing_f_contrac_70314a_idx"),
        ),
        migrations.AddIndex(
            model_name="filingsession",
            index=models.Index(fields=["user", "-created_at"], name="oa_filing_f_user_id_00853f_idx"),
        ),
        migrations.AddIndex(
            model_name="filingsession",
            index=models.Index(fields=["status", "-created_at"], name="oa_filing_f_status_19177a_idx"),
        ),
        migrations.AddIndex(
            model_name="automationscript",
            index=models.Index(fields=["oa_config", "-created_at"], name="oa_filing_a_oa_conf_e4f706_idx"),
        ),
    ]
