# Generated by Django 6.0.2 on 2026-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oa_filing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oaconfig",
            name="base_url",
        ),
        migrations.RemoveField(
            model_name="oaconfig",
            name="login_path",
        ),
        migrations.AddField(
            model_name="oaconfig",
            name="site_name",
            field=models.CharField(
                default="",
                help_text="与账号密码管理中的「网站名称」一致，用于自动匹配凭证",
                max_length=255,
                verbose_name="凭证站点名称",
            ),
        ),
    ]
