# Generated by Django 6.0.2 on 2026-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oa_filing", "0002_remove_oaconfig_base_url_remove_oaconfig_login_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oaconfig",
            name="oa_system_name",
        ),
    ]
