# Generated by Django 6.0.2 on 2026-02-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oa_filing", "0003_remove_oaconfig_oa_system_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="oaconfig",
            name="oa_filing_o_law_fir_5d5654_idx",
        ),
        migrations.AlterField(
            model_name="oaconfig",
            name="site_name",
            field=models.CharField(
                help_text="与账号密码管理中的「网站名称」一致，用于自动匹配凭证",
                max_length=255,
                unique=True,
                verbose_name="凭证站点名称",
            ),
        ),
        migrations.AddIndex(
            model_name="oaconfig",
            index=models.Index(fields=["is_enabled"], name="oa_filing_o_is_enab_323799_idx"),
        ),
        migrations.RemoveField(
            model_name="oaconfig",
            name="law_firm",
        ),
    ]
