# Generated by Django 6.0.2 on 2026-02-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oa_filing", "0004_remove_oaconfig_oa_filing_o_law_fir_5d5654_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filingsession",
            options={"verbose_name": "立案记录", "verbose_name_plural": "立案记录"},
        ),
        migrations.RemoveField(
            model_name="filingsession",
            name="last_screenshot",
        ),
        migrations.RemoveField(
            model_name="filingsession",
            name="steps_data",
        ),
        migrations.AlterField(
            model_name="filingsession",
            name="automation_script",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="oa_filing.automationscript",
                verbose_name="执行脚本",
            ),
        ),
        migrations.AlterField(
            model_name="filingsession",
            name="error_message",
            field=models.TextField(blank=True, default="", verbose_name="错误信息"),
        ),
    ]
