# Generated by Django 6.0.2 on 2026-02-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oa_filing", "0005_alter_filingsession_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="automationscript",
            name="oa_filing_a_oa_conf_e4f706_idx",
        ),
        migrations.RemoveField(
            model_name="filingsession",
            name="automation_script",
        ),
        migrations.DeleteModel(
            name="AutomationScript",
        ),
    ]
