# Generated by Django 6.0.2 on 2026-03-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oa_filing", "0006_remove_automationscript_oa_filing_a_oa_conf_e4f706_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filingsession",
            name="oa_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filing_sessions",
                to="oa_filing.oaconfig",
                verbose_name="OA配置",
            ),
        ),
    ]
