# Generated by Django 6.0.2 on 2026-03-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_cascade_delete_case_on_contract_delete"),
        ("oa_filing", "0007_alter_filingsession_oa_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filingsession",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filing_sessions",
                to="cases.case",
                verbose_name="案件",
            ),
        ),
    ]
