# Generated by Django 6.0.2 on 2026-03-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oa_filing", "0009_add_client_import_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientimportsession",
            name="discovered_count",
            field=models.IntegerField(default=0, verbose_name="已发现数量"),
        ),
        migrations.AddField(
            model_name="clientimportsession",
            name="phase",
            field=models.CharField(
                choices=[
                    ("pending", "待开始"),
                    ("discovering", "查找并发现"),
                    ("importing", "导入中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=16,
                verbose_name="阶段",
            ),
        ),
        migrations.AddField(
            model_name="clientimportsession",
            name="progress_message",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="进度描述"),
        ),
    ]
