# Generated by Django 6.0.2 on 2026-03-25 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oa_filing", "0010_clientimportsession_progress_fields"),
        ("organization", "0002_remove_is_preferred"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseImportSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开始"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("pending", "待开始"),
                            ("parsing", "解析中"),
                            ("preview", "预览中"),
                            ("discovering", "查找中"),
                            ("importing", "导入中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="阶段",
                    ),
                ),
                (
                    "uploaded_filename",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="上传文件名"),
                ),
                ("total_count", models.IntegerField(default=0, verbose_name="总案件数")),
                ("matched_count", models.IntegerField(default=0, verbose_name="已匹配数")),
                ("unmatched_count", models.IntegerField(default=0, verbose_name="未匹配数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功数量")),
                ("skip_count", models.IntegerField(default=0, verbose_name="跳过数量")),
                ("error_count", models.IntegerField(default=0, verbose_name="错误数量")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("progress_message", models.CharField(blank=True, default="", max_length=255, verbose_name="进度描述")),
                ("result_data", models.JSONField(default=dict, verbose_name="结果数据")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "credential",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_import_sessions",
                        to="organization.accountcredential",
                        verbose_name="OA凭证",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_import_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件导入记录",
                "verbose_name_plural": "案件导入记录",
                "indexes": [
                    models.Index(fields=["lawyer", "-created_at"], name="oa_filing_c_lawyer__3c2fe4_idx"),
                    models.Index(fields=["status", "-created_at"], name="oa_filing_c_status_a85172_idx"),
                ],
            },
        ),
    ]
