# Generated by Django 6.0.3 on 2026-04-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa_filing', '0011_add_case_import_session'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caseimportsession',
            name='oa_filing_c_lawyer__3c2fe4_idx',
        ),
        migrations.RemoveIndex(
            model_name='caseimportsession',
            name='oa_filing_c_status_a85172_idx',
        ),
    ]
