# Generated by Django 6.0.3 on 2026-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Evidence Sorting', max_length=64)),
            ],
            options={
                'verbose_name': '案件材料整理',
                'verbose_name_plural': '案件材料整理',
                'managed': False,
            },
        ),
    ]
