# Generated by Django 6.0.2 on 2026-02-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="联系电话")),
                ("address", models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="住所地")),
                (
                    "client_type",
                    models.CharField(
                        choices=[("natural", "自然人"), ("legal", "法人"), ("non_legal_org", "非法人组织")],
                        default="legal",
                        max_length=16,
                        verbose_name="主体类型",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=64, null=True, unique=True, verbose_name="身份证号码或统一社会信用代码"
                    ),
                ),
                (
                    "legal_representative",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="法定代表人或负责人"),
                ),
                (
                    "legal_representative_id_number",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="法定代表人/负责人身份证号码"),
                ),
                ("is_our_client", models.BooleanField(default=False, verbose_name="是否为我方当事人")),
            ],
            options={
                "verbose_name": "当事人",
                "verbose_name_plural": "当事人",
                "db_table": "cases_client",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ClientIdentityDoc",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("id_card", "身份证"),
                            ("passport", "护照"),
                            ("hk_macao_permit", "港澳通行证"),
                            ("residence_permit", "居住证"),
                            ("household_register", "户口本"),
                            ("business_license", "营业执照"),
                            ("legal_rep_id_card", "法定代表人/负责人身份证"),
                        ],
                        max_length=32,
                        verbose_name="证件类型",
                    ),
                ),
                ("file_path", models.CharField(max_length=512, verbose_name="文件路径")),
                ("expiry_date", models.DateField(blank=True, null=True, verbose_name="到期日期")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_docs",
                        to="client.client",
                        verbose_name="当事人",
                    ),
                ),
            ],
            options={
                "verbose_name": "当事人证件文件",
                "verbose_name_plural": "当事人证件文件",
                "db_table": "cases_clientidentitydoc",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PropertyClue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "clue_type",
                    models.CharField(
                        choices=[
                            ("bank", "银行账户"),
                            ("alipay", "支付宝账户"),
                            ("wechat", "微信账户"),
                            ("real_estate", "不动产"),
                            ("other", "其他"),
                        ],
                        default="bank",
                        max_length=16,
                        verbose_name="线索类型",
                    ),
                ),
                ("content", models.TextField(blank=True, default="", verbose_name="线索内容")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_clues",
                        to="client.client",
                        verbose_name="当事人",
                    ),
                ),
            ],
            options={
                "verbose_name": "财产线索",
                "verbose_name_plural": "财产线索",
                "db_table": "cases_propertyclue",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PropertyClueAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=512, verbose_name="文件路径")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                (
                    "property_clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="client.propertyclue",
                        verbose_name="财产线索",
                    ),
                ),
            ],
            options={
                "verbose_name": "财产线索附件",
                "verbose_name_plural": "财产线索附件",
                "db_table": "cases_propertyclueattachment",
                "managed": True,
            },
        ),
    ]
