# Generated by Django 6.0.2 on 2026-03-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientidentitydoc",
            options={"managed": True, "verbose_name": "证件", "verbose_name_plural": "证件"},
        ),
    ]
