# Generated by Django 6.0.2 on 2026-03-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_clientidentitydoc_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id_number",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="身份证号码或统一社会信用代码"),
        ),
    ]
