# Generated by Django 6.0.2 on 2026-03-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_client_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=64, null=True, unique=True, verbose_name="身份证号码或统一社会信用代码"
            ),
        ),
    ]
