# Generated by Django 6.0.4 on 2026-04-25 07:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_client_id_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalClient",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="联系电话")),
                ("address", models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="住所地")),
                (
                    "client_type",
                    models.CharField(
                        choices=[("natural", "自然人"), ("legal", "法人"), ("non_legal_org", "非法人组织")],
                        default="legal",
                        max_length=16,
                        verbose_name="主体类型",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, verbose_name="身份证号码或统一社会信用代码"
                    ),
                ),
                (
                    "legal_representative",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="法定代表人或负责人"),
                ),
                (
                    "legal_representative_id_number",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="法定代表人/负责人身份证号码"),
                ),
                ("is_our_client", models.BooleanField(default=False, verbose_name="是否为我方当事人")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 当事人",
                "verbose_name_plural": "historical 当事人",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
