# Generated by Django 6.0.5 on 2026-05-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_add_identity_doc_composite_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='cases_clien_client__ffed22_idx'),
        ),
    ]
