# Generated by Django 6.0.2 on 2026-02-28 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Document Processor", max_length=64)),
            ],
            options={
                "verbose_name": "文档处理",
                "verbose_name_plural": "文档处理",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FeeNoticeTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Fee Notice Test", max_length=64)),
            ],
            options={
                "verbose_name": "交费通知书识别",
                "verbose_name_plural": "交费通知书识别",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImageRotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Image Rotation", max_length=64)),
            ],
            options={
                "verbose_name": "图片自动旋转",
                "verbose_name_plural": "图片自动旋转",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NamerTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Namer Tool", max_length=64)),
            ],
            options={
                "verbose_name": "自动命名工具",
                "verbose_name_plural": "自动命名工具",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PreservationDateTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Preservation Date Test", max_length=64)),
            ],
            options={
                "verbose_name": "财产保全日期识别",
                "verbose_name_plural": "财产保全日期识别",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TestCourt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Test Court", max_length=64)),
            ],
            options={
                "verbose_name": "测试法院系统",
                "verbose_name_plural": "测试法院系统",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TestToolsHub",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Test Tools Hub", max_length=64)),
            ],
            options={
                "verbose_name": "测试工具",
                "verbose_name_plural": "测试工具",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuickDownloadTool",
            fields=[],
            options={
                "verbose_name": "快速下载文书",
                "verbose_name_plural": "快速下载文书",
                "managed": False,
                "proxy": True,
            },
            bases=("automation.namertool",),
        ),
        migrations.CreateModel(
            name="CourtSMS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="短信内容")),
                ("received_at", models.DateTimeField(verbose_name="收到时间")),
                (
                    "sms_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document_delivery", "文书送达"),
                            ("info_notification", "信息通知"),
                            ("filing_notification", "立案通知"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="短信类型",
                    ),
                ),
                ("download_links", models.JSONField(default=list, verbose_name="下载链接列表")),
                ("case_numbers", models.JSONField(default=list, verbose_name="案号列表")),
                ("party_names", models.JSONField(default=list, verbose_name="当事人名称列表")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("parsing", "解析中"),
                            ("downloading", "下载中"),
                            ("download_failed", "下载失败"),
                            ("matching", "匹配中"),
                            ("pending_manual", "待人工处理"),
                            ("renaming", "重命名中"),
                            ("notifying", "通知中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="处理状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                ("feishu_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="飞书发送时间")),
                ("feishu_error", models.TextField(blank=True, null=True, verbose_name="飞书发送错误")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="court_sms_records",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "case_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="court_sms_records",
                        to="cases.caselog",
                        verbose_name="案件日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "法院短信",
                "verbose_name_plural": "法院短信",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRecognitionProxy",
            fields=[],
            options={
                "verbose_name": "文书智能识别",
                "verbose_name_plural": "文书智能识别",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("automation.courtsms",),
        ),
        migrations.CreateModel(
            name="CourtToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(help_text="如:court_zxfw", max_length=128, verbose_name="网站名称")),
                ("account", models.CharField(max_length=128, verbose_name="账号")),
                ("token", models.TextField(help_text="JWT Token 或其他认证令牌", verbose_name="Token")),
                (
                    "token_type",
                    models.CharField(
                        default="Bearer", help_text="如:Bearer, JWT", max_length=32, verbose_name="Token 类型"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "Token管理",
                "verbose_name_plural": "Token管理",
                "indexes": [
                    models.Index(fields=["site_name", "account"], name="automation__site_na_a7e54a_idx"),
                    models.Index(fields=["expires_at"], name="automation__expires_0932b8_idx"),
                ],
                "unique_together": {("site_name", "account")},
            },
        ),
        migrations.CreateModel(
            name="InvoiceRecognitionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("merge_config", models.JSONField(blank=True, default=list, verbose_name="分组合并配置")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_recognition_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票识别任务",
                "verbose_name_plural": "发票识别任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=1024, verbose_name="文件路径")),
                ("original_filename", models.CharField(max_length=255, verbose_name="原始文件名")),
                ("invoice_code", models.CharField(blank=True, default="", max_length=50, verbose_name="发票代码")),
                ("invoice_number", models.CharField(blank=True, default="", max_length=50, verbose_name="发票号码")),
                ("invoice_date", models.DateField(blank=True, null=True, verbose_name="开票日期")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="金额（不含税）"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="税额"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="价税合计"
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, default="", max_length=255, verbose_name="购买方名称")),
                ("seller_name", models.CharField(blank=True, default="", max_length=255, verbose_name="销售方名称")),
                ("project_name", models.CharField(blank=True, default="", max_length=255, verbose_name="项目名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vat_special", "增值税专用发票"),
                            ("vat_normal", "增值税普通发票"),
                            ("vat_electronic", "增值税电子普通发票"),
                            ("vehicle_sales", "机动车销售统一发票"),
                            ("train_ticket", "火车票"),
                            ("taxi_receipt", "出租车发票"),
                            ("quota_invoice", "定额发票"),
                            ("air_itinerary", "飞机行程单"),
                            ("toll_receipt", "过路费发票"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="发票类目",
                    ),
                ),
                ("raw_text", models.TextField(blank=True, default="", verbose_name="OCR 原始文本")),
                ("is_duplicate", models.BooleanField(default=False, verbose_name="是否重复")),
                ("duplicate_of_id", models.IntegerField(blank=True, null=True, verbose_name="重复的原始记录ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待识别"), ("success", "识别成功"), ("failed", "识别失败")],
                        default="pending",
                        max_length=32,
                        verbose_name="识别状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="automation.invoicerecognitiontask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票记录",
                "verbose_name_plural": "发票记录",
            },
        ),
        migrations.CreateModel(
            name="PreservationQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "preserve_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="需要保全的财产金额", max_digits=15, verbose_name="保全金额"
                    ),
                ),
                (
                    "corp_id",
                    models.CharField(
                        default="2550", help_text="法院系统中的法院标识", max_length=32, verbose_name="法院ID"
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        default="127000", help_text="保全分类ID (cPid)", max_length=32, verbose_name="分类ID"
                    ),
                ),
                (
                    "credential_id",
                    models.IntegerField(
                        blank=True,
                        help_text="关联的账号凭证ID(可选,系统会自动获取Token)",
                        null=True,
                        verbose_name="凭证ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("partial_success", "部分成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                ("total_companies", models.IntegerField(default=0, verbose_name="保险公司总数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功查询数")),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败查询数")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
            ],
            options={
                "verbose_name": "财产保全询价",
                "verbose_name_plural": "财产保全询价",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="automation__status_52dbb3_idx"),
                    models.Index(fields=["credential_id"], name="automation__credent_02ffc0_idx"),
                    models.Index(fields=["created_at"], name="automation__created_b495d2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsuranceQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_id", models.CharField(help_text="cId", max_length=64, verbose_name="保险公司ID")),
                ("company_code", models.CharField(help_text="cCode", max_length=64, verbose_name="保险公司编码")),
                ("company_name", models.CharField(help_text="cName", max_length=256, verbose_name="保险公司名称")),
                (
                    "premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="保险公司给出的担保费报价(通常使用 minPremium)",
                        max_digits=15,
                        null=True,
                        verbose_name="报价金额",
                    ),
                ),
                (
                    "min_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="minPremium",
                        max_digits=15,
                        null=True,
                        verbose_name="最低收费1",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="minAmount",
                        max_digits=15,
                        null=True,
                        verbose_name="最低收费2",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="maxAmount",
                        max_digits=15,
                        null=True,
                        verbose_name="最高收费",
                    ),
                ),
                (
                    "min_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="minRate",
                        max_digits=10,
                        null=True,
                        verbose_name="最低费率",
                    ),
                ),
                (
                    "max_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="maxRate",
                        max_digits=10,
                        null=True,
                        verbose_name="最高费率",
                    ),
                ),
                (
                    "max_apply_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="maxApplyAmount",
                        max_digits=15,
                        null=True,
                        verbose_name="最高保全金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")], max_length=32, verbose_name="查询状态"
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, help_text="API 返回的完整响应数据", null=True, verbose_name="完整响应"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "preservation_quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="automation.preservationquote",
                        verbose_name="询价任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "保险公司报价",
                "verbose_name_plural": "保险公司报价",
                "ordering": ["min_amount"],
            },
        ),
        migrations.CreateModel(
            name="ScraperTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("court_document", "下载司法文书"),
                            ("court_filing", "自动立案"),
                            ("justice_bureau", "司法局操作"),
                            ("police", "公安局操作"),
                        ],
                        max_length=32,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "等待中"), ("running", "执行中"), ("success", "成功"), ("failed", "失败")],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=5, help_text="1-10,数字越小优先级越高", verbose_name="优先级"),
                ),
                ("url", models.URLField(verbose_name="目标URL")),
                ("config", models.JSONField(default=dict, help_text="存储账号、密码、文件路径等", verbose_name="配置")),
                ("result", models.JSONField(blank=True, null=True, verbose_name="执行结果")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                ("max_retries", models.IntegerField(default=3, verbose_name="最大重试次数")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="留空则立即执行", null=True, verbose_name="计划执行时间"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraper_tasks",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务管理",
                "verbose_name_plural": "任务管理",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="courtsms",
            name="scraper_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="court_sms_records",
                to="automation.scrapertask",
                verbose_name="下载任务",
            ),
        ),
        migrations.CreateModel(
            name="CourtDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("c_sdbh", models.CharField(max_length=128, verbose_name="送达编号")),
                ("c_stbh", models.CharField(max_length=512, verbose_name="上传编号")),
                ("wjlj", models.URLField(max_length=1024, verbose_name="文件链接")),
                ("c_wsbh", models.CharField(max_length=128, verbose_name="文书编号")),
                ("c_wsmc", models.CharField(max_length=512, verbose_name="文书名称")),
                ("c_fybh", models.CharField(max_length=64, verbose_name="法院编号")),
                ("c_fymc", models.CharField(max_length=256, verbose_name="法院名称")),
                ("c_wjgs", models.CharField(max_length=32, verbose_name="文件格式")),
                ("dt_cjsj", models.DateTimeField(verbose_name="创建时间(原始)")),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("pending", "待下载"),
                            ("downloading", "下载中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="下载状态",
                    ),
                ),
                (
                    "local_file_path",
                    models.CharField(blank=True, max_length=1024, null=True, verbose_name="本地文件路径"),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True, verbose_name="文件大小(字节)")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("downloaded_at", models.DateTimeField(blank=True, null=True, verbose_name="下载完成时间")),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="court_documents",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "scraper_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="automation.scrapertask",
                        verbose_name="爬虫任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "法院文书",
                "verbose_name_plural": "法院文书",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenAcquisitionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(help_text="如:court_zxfw", max_length=128, verbose_name="网站名称")),
                ("account", models.CharField(max_length=128, verbose_name="使用账号")),
                (
                    "credential_id",
                    models.IntegerField(
                        blank=True, help_text="关联的AccountCredential ID", null=True, verbose_name="凭证ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("network_error", "网络错误"),
                            ("captcha_error", "验证码错误"),
                            ("credential_error", "账号密码错误"),
                        ],
                        max_length=32,
                        verbose_name="获取状态",
                    ),
                ),
                (
                    "trigger_reason",
                    models.CharField(
                        help_text="如:token_expired, no_token, manual_trigger", max_length=256, verbose_name="触发原因"
                    ),
                ),
                ("attempt_count", models.IntegerField(default=1, verbose_name="尝试次数")),
                ("total_duration", models.FloatField(blank=True, null=True, verbose_name="总耗时(秒)")),
                ("login_duration", models.FloatField(blank=True, null=True, verbose_name="登录耗时(秒)")),
                ("captcha_attempts", models.IntegerField(default=0, verbose_name="验证码尝试次数")),
                ("network_retries", models.IntegerField(default=0, verbose_name="网络重试次数")),
                (
                    "token_preview",
                    models.CharField(
                        blank=True, help_text="Token的前50个字符", max_length=50, null=True, verbose_name="Token预览"
                    ),
                ),
                (
                    "token_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Token的SHA256指纹(用于排查重复/归因,不可反推Token)",
                        max_length=64,
                        null=True,
                        verbose_name="Token指纹",
                    ),
                ),
                (
                    "token_redacted",
                    models.CharField(
                        blank=True,
                        help_text="脱敏后的Token摘要(仅用于人工排查)",
                        max_length=32,
                        null=True,
                        verbose_name="Token脱敏摘要",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, help_text="包含完整的错误堆栈和上下文", null=True, verbose_name="详细错误信息"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
            ],
            options={
                "verbose_name": "Token获取历史",
                "verbose_name_plural": "Token获取历史",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["site_name", "-created_at"], name="automation__site_na_26069d_idx"),
                    models.Index(fields=["account", "-created_at"], name="automation__account_c5ade7_idx"),
                    models.Index(fields=["status", "-created_at"], name="automation__status_25b8dd_idx"),
                    models.Index(fields=["credential_id"], name="automation__credent_835e13_idx"),
                    models.Index(fields=["created_at"], name="automation__created_81fc82_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentDeliverySchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("runs_per_day", models.PositiveIntegerField(default=1, verbose_name="每天运行次数")),
                (
                    "hour_interval",
                    models.PositiveIntegerField(
                        default=24, help_text="在24小时内的运行间隔", verbose_name="运行间隔(小时)"
                    ),
                ),
                (
                    "cutoff_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="只处理最近N小时内的文书", verbose_name="截止时间(小时)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="上次运行时间")),
                ("next_run_at", models.DateTimeField(blank=True, null=True, verbose_name="下次运行时间")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_schedules",
                        to="organization.accountcredential",
                        verbose_name="账号凭证",
                    ),
                ),
            ],
            options={
                "verbose_name": "文书送达定时任务",
                "verbose_name_plural": "文书送达定时任务",
                "indexes": [
                    models.Index(fields=["is_active", "next_run_at"], name="automation__is_acti_ebd2c4_idx"),
                    models.Index(fields=["credential"], name="automation__credent_eb5b93_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentQueryHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_number", models.CharField(max_length=128, verbose_name="案号")),
                ("send_time", models.DateTimeField(verbose_name="文书发送时间")),
                ("queried_at", models.DateTimeField(auto_now_add=True, verbose_name="查询时间")),
                (
                    "court_sms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="query_histories",
                        to="automation.courtsms",
                        verbose_name="关联短信记录",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_query_histories",
                        to="organization.accountcredential",
                        verbose_name="账号凭证",
                    ),
                ),
            ],
            options={
                "verbose_name": "文书查询历史",
                "verbose_name_plural": "文书查询历史",
                "indexes": [
                    models.Index(fields=["credential", "case_number"], name="automation__credent_76d5df_idx"),
                    models.Index(fields=["send_time"], name="automation__send_ti_17ce8b_idx"),
                ],
                "unique_together": {("credential", "case_number", "send_time")},
            },
        ),
        migrations.CreateModel(
            name="DocumentRecognitionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=1024, verbose_name="文件路径")),
                ("original_filename", models.CharField(max_length=256, verbose_name="原始文件名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "识别中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                ("document_type", models.CharField(blank=True, max_length=32, null=True, verbose_name="文书类型")),
                ("case_number", models.CharField(blank=True, max_length=128, null=True, verbose_name="案号")),
                ("key_time", models.DateTimeField(blank=True, null=True, verbose_name="关键时间")),
                ("confidence", models.FloatField(blank=True, null=True, verbose_name="置信度")),
                ("extraction_method", models.CharField(blank=True, max_length=32, null=True, verbose_name="提取方式")),
                ("raw_text", models.TextField(blank=True, null=True, verbose_name="原始文本")),
                (
                    "renamed_file_path",
                    models.CharField(blank=True, max_length=1024, null=True, verbose_name="重命名后路径"),
                ),
                ("binding_success", models.BooleanField(null=True, verbose_name="绑定成功")),
                ("binding_message", models.CharField(blank=True, max_length=512, null=True, verbose_name="绑定消息")),
                (
                    "binding_error_code",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="绑定错误码"),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("notification_sent", models.BooleanField(default=False, verbose_name="通知已发送")),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="通知发送时间")),
                ("notification_error", models.TextField(blank=True, null=True, verbose_name="通知错误信息")),
                ("notification_file_sent", models.BooleanField(default=False, verbose_name="文件已发送")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_tasks",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "case_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_tasks",
                        to="cases.caselog",
                        verbose_name="案件日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "文书识别任务",
                "verbose_name_plural": "文书识别任务",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="automation__status_b57405_idx"),
                    models.Index(fields=["case"], name="automation__case_id_13ae57_idx"),
                    models.Index(fields=["notification_sent"], name="automation__notific_6b9b00_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoicerecognitiontask",
            index=models.Index(fields=["status", "-created_at"], name="automation__status_806e2d_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(fields=["invoice_code", "invoice_number"], name="automation__invoice_7bceb1_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicerecord",
            index=models.Index(fields=["task", "category"], name="automation__task_id_71663a_idx"),
        ),
        migrations.AddIndex(
            model_name="insurancequote",
            index=models.Index(fields=["preservation_quote", "status"], name="automation__preserv_2151c4_idx"),
        ),
        migrations.AddIndex(
            model_name="insurancequote",
            index=models.Index(fields=["company_id"], name="automation__company_fa0a40_idx"),
        ),
        migrations.AddIndex(
            model_name="insurancequote",
            index=models.Index(fields=["premium"], name="automation__premium_2be329_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapertask",
            index=models.Index(fields=["status", "priority", "-created_at"], name="automation__status_381714_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapertask",
            index=models.Index(fields=["task_type"], name="automation__task_ty_53ba98_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapertask",
            index=models.Index(fields=["case"], name="automation__case_id_3547a7_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapertask",
            index=models.Index(fields=["scheduled_at"], name="automation__schedul_080d53_idx"),
        ),
        migrations.AddIndex(
            model_name="courtsms",
            index=models.Index(fields=["status", "-received_at"], name="automation__status_30d0f7_idx"),
        ),
        migrations.AddIndex(
            model_name="courtsms",
            index=models.Index(fields=["sms_type"], name="automation__sms_typ_04630f_idx"),
        ),
        migrations.AddIndex(
            model_name="courtsms",
            index=models.Index(fields=["case"], name="automation__case_id_4acbbe_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["scraper_task", "download_status"], name="automation__scraper_7a7f42_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["case"], name="automation__case_id_1e84f1_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["c_wsbh"], name="automation__c_wsbh_6d4b1c_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["c_fymc"], name="automation__c_fymc_c87d06_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["download_status"], name="automation__downloa_cf5e16_idx"),
        ),
        migrations.AddIndex(
            model_name="courtdocument",
            index=models.Index(fields=["created_at"], name="automation__created_b4f148_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="courtdocument",
            unique_together={("c_wsbh", "c_sdbh")},
        ),
    ]
