# Generated by Django 6.0.2 on 2026-03-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GsxtReportTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=255, verbose_name="企业名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("waiting_captcha", "等待验证码"),
                            ("waiting_email", "等待邮件"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="gsxt_reports/", verbose_name="报告文件"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsxt_report_tasks",
                        to="client.client",
                        verbose_name="当事人",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业信用报告任务",
                "verbose_name_plural": "企业信用报告任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
