# Generated by Django 6.0.2 on 2026-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_gsxt_report_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="gsxtreporttask",
            name="credit_code",
            field=models.CharField(blank=True, max_length=64, verbose_name="统一社会信用代码"),
        ),
    ]
