# Generated by Django 6.0.2 on 2026-03-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_add_credit_code_to_gsxt_report_task'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentrecognitiontask',
            name='automation__status_b57405_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentrecognitiontask',
            name='automation__case_id_13ae57_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentrecognitiontask',
            name='automation__notific_6b9b00_idx',
        ),
        migrations.DeleteModel(
            name='FeeNoticeTest',
        ),
        migrations.DeleteModel(
            name='PreservationDateTest',
        ),
        migrations.DeleteModel(
            name='DocumentRecognitionProxy',
        ),
        migrations.AlterModelOptions(
            name='courttoken',
            options={'verbose_name': '一张网/保全Token管理', 'verbose_name_plural': '一张网/保全Token管理'},
        ),
        migrations.AlterModelOptions(
            name='tokenacquisitionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': '一张网/保全Token获取历史', 'verbose_name_plural': '一张网/保全Token获取历史'},
        ),
        migrations.AlterField(
            model_name='courttoken',
            name='account',
            field=models.CharField(max_length=128, verbose_name='登录账号'),
        ),
        migrations.AlterField(
            model_name='courttoken',
            name='site_name',
            field=models.CharField(help_text='如:court_zxfw（人民法院在线服务网/一张网）, court_baoquan（保全系统）', max_length=128, verbose_name='站点标识'),
        ),
        migrations.AlterField(
            model_name='courttoken',
            name='token',
            field=models.TextField(help_text='一张网/保全系统返回的 JWT Token 或其他认证令牌', verbose_name='认证Token'),
        ),
        migrations.AlterField(
            model_name='courttoken',
            name='token_type',
            field=models.CharField(default='Bearer', help_text='如:Bearer, JWT', max_length=32, verbose_name='Token类型'),
        ),
        migrations.AlterField(
            model_name='tokenacquisitionhistory',
            name='site_name',
            field=models.CharField(help_text='如:court_zxfw（人民法院在线服务网/一张网）, court_baoquan（保全系统）', max_length=128, verbose_name='站点标识'),
        ),
        migrations.AlterField(
            model_name='tokenacquisitionhistory',
            name='token_preview',
            field=models.CharField(blank=True, help_text='Token 前50个字符', max_length=50, null=True, verbose_name='Token预览'),
        ),
        migrations.DeleteModel(
            name='DocumentRecognitionTask',
        ),
    ]
