# Generated by Django 6.0.2 on 2026-03-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0006_create_documentrecognitiontask_table_sql"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courttoken",
            options={"verbose_name": "一张网保全Token管理", "verbose_name_plural": "一张网保全Token管理"},
        ),
    ]
