# Generated by Django 6.0.3 on 2026-04-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0007_rename_token_verbose"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courttoken",
            options={"verbose_name": "一张网Token管理", "verbose_name_plural": "一张网Token管理"},
        ),
    ]
