# Generated by Django 6.0.3 on 2026-04-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0009_case_preservation_quote_binding"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="casepreservationquotebinding",
            new_name="automation__case_id_3de3aa_idx",
            old_name="automation__case_id_6f343e_idx",
        ),
        migrations.RenameIndex(
            model_name="casepreservationquotebinding",
            new_name="automation__preserv_9ba9c7_idx",
            old_name="automation__preserv_69b108_idx",
        ),
        migrations.RenameIndex(
            model_name="casepreservationquotebinding",
            new_name="automation__preserv_3df2f3_idx",
            old_name="automation__preserv_2b8c06_idx",
        ),
    ]
