# Generated by Django 6.0.4 on 2026-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0010_rename_automation__case_id_6f343e_idx_automation__case_id_3de3aa_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtsms",
            name="document_file_paths",
            field=models.JSONField(default=list, verbose_name="文书文件路径列表"),
        ),
    ]
