# Generated by Django 6.0.4 on 2026-04-15 10:43

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0011_courtsms_document_file_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtsms",
            name="delivery_event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="送达事件标识",
            ),
        ),
        migrations.AddField(
            model_name="courtsms",
            name="delivery_event_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="送达事件去重键",
            ),
        ),
        migrations.AddConstraint(
            model_name="courtsms",
            constraint=models.UniqueConstraint(
                fields=("delivery_event_key",),
                condition=Q(delivery_event_key__isnull=False) & ~Q(delivery_event_key=""),
                name="uniq_courtsms_delivery_event_key",
            ),
        ),
    ]
