# Generated by Django 6.0.2 on 2026-03-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="McpWorkbench",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="MCP Workbench", max_length=64)),
            ],
            options={
                "verbose_name": "MCP 调试工作台",
                "verbose_name_plural": "MCP 调试工作台",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="McpWorkbenchExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=64, verbose_name="Provider")),
                ("tool_name", models.CharField(max_length=128, verbose_name="工具名称")),
                ("arguments", models.JSONField(blank=True, default=dict, verbose_name="请求参数")),
                ("response_data", models.JSONField(blank=True, default=dict, verbose_name="响应数据")),
                ("response_raw", models.JSONField(blank=True, default=dict, verbose_name="原始响应")),
                ("response_meta", models.JSONField(blank=True, default=dict, verbose_name="响应元信息")),
                ("success", models.BooleanField(default=False, verbose_name="是否成功")),
                ("error_code", models.CharField(blank=True, default="", max_length=64, verbose_name="错误码")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("duration_ms", models.PositiveIntegerField(default=0, verbose_name="耗时(毫秒)")),
                (
                    "requested_transport",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="请求协议"),
                ),
                ("actual_transport", models.CharField(blank=True, default="", max_length=32, verbose_name="实际协议")),
                ("operator_username", models.CharField(blank=True, default="", max_length=150, verbose_name="操作人")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "replay_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replayed_records",
                        to="enterprise_data.mcpworkbenchexecution",
                        verbose_name="重放来源",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP 调试执行历史",
                "verbose_name_plural": "MCP 调试执行历史",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "tool_name", "-created_at"], name="enterprise__provide_9eddea_idx"
                    ),
                    models.Index(fields=["success", "-created_at"], name="enterprise__success_107252_idx"),
                    models.Index(fields=["operator_username", "-created_at"], name="enterprise__operato_e5e0e9_idx"),
                ],
            },
        ),
    ]
