# Generated by Django 6.0.2 on 2026-02-27 04:11

import apps.core.filesystem.storage
import apps.organization.models.lawyer
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawFirm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="律所名称")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="地址")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="联系电话")),
                ("social_credit_code", models.CharField(blank=True, max_length=18, verbose_name="统一社会信用代码")),
                ("bank_name", models.CharField(blank=True, max_length=255, verbose_name="开户行")),
                ("bank_account", models.CharField(blank=True, max_length=64, verbose_name="银行账号")),
            ],
            options={
                "verbose_name": "律所",
                "verbose_name_plural": "律所",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="团队名称")),
                (
                    "team_type",
                    models.CharField(
                        choices=[("lawyer", "律师团队"), ("biz", "业务团队")], max_length=16, verbose_name="团队类型"
                    ),
                ),
                (
                    "law_firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="organization.lawfirm",
                        verbose_name="所属律所",
                    ),
                ),
            ],
            options={
                "verbose_name": "团队",
                "verbose_name_plural": "团队",
            },
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("real_name", models.CharField(blank=True, max_length=255, verbose_name="真实姓名")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="手机号码")),
                ("license_no", models.CharField(blank=True, max_length=64, verbose_name="执业证号")),
                ("id_card", models.CharField(blank=True, max_length=32, verbose_name="身份证号")),
                ("is_admin", models.BooleanField(default=False, verbose_name="是否律所管理员")),
                (
                    "license_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=apps.core.filesystem.storage.KeepOriginalNameStorage(),
                        upload_to=apps.organization.models.lawyer.lawyer_license_upload_path,
                        validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                        verbose_name="执业证文件",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "law_firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lawyers",
                        to="organization.lawfirm",
                        verbose_name="所属律所",
                    ),
                ),
                (
                    "biz_teams",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"team_type": "biz"},
                        related_name="biz_members",
                        to="organization.team",
                        verbose_name="所属业务团队",
                    ),
                ),
                (
                    "lawyer_teams",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"team_type": "lawyer"},
                        related_name="lawyers",
                        to="organization.team",
                        verbose_name="所属律师团队",
                    ),
                ),
            ],
            options={
                "verbose_name": "律师",
                "verbose_name_plural": "律师",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AccountCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_name", models.CharField(max_length=255, verbose_name="网站名称")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("account", models.CharField(max_length=255, verbose_name="账号")),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("last_login_success_at", models.DateTimeField(blank=True, null=True, verbose_name="最后成功登录时间")),
                ("login_success_count", models.PositiveIntegerField(default=0, verbose_name="成功登录次数")),
                ("login_failure_count", models.PositiveIntegerField(default=0, verbose_name="失败登录次数")),
                ("is_preferred", models.BooleanField(default=False, verbose_name="是否优先使用")),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="律师",
                    ),
                ),
            ],
            options={
                "verbose_name": "账号密码",
                "verbose_name_plural": "账号密码",
                "ordering": ["-last_login_success_at", "-login_success_count", "login_failure_count"],
                "indexes": [
                    models.Index(fields=["site_name", "-last_login_success_at"], name="organizatio_site_na_b29cd0_idx"),
                    models.Index(fields=["site_name", "is_preferred"], name="organizatio_site_na_ba8d77_idx"),
                ],
            },
        ),
    ]
