# Generated by Django 6.0.2 on 2026-03-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accountcredential",
            name="organizatio_site_na_ba8d77_idx",
        ),
        migrations.RemoveField(
            model_name="accountcredential",
            name="is_preferred",
        ),
    ]
