# Generated by Django 6.0.4 on 2026-04-29 05:41

from django.db import migrations, models


def clear_empty_emails(apps, schema_editor):
    """将空字符串的 email 更新为 NULL"""
    Lawyer = apps.get_model("organization", "Lawyer")
    Lawyer.objects.filter(email="").update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_remove_is_preferred"),
    ]

    operations = [
        # Step 1: 先修改字段为允许 NULL（不添加唯一约束）
        migrations.AlterField(
            model_name="lawyer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="email address",
            ),
        ),
        # Step 2: 清理空 email 值
        migrations.RunPython(clear_empty_emails, migrations.RunPython.noop),
        # Step 3: 添加唯一约束
        migrations.AlterField(
            model_name="lawyer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
