# Generated by Django 6.0.4 on 2026-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_lawyer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='真实姓名'),
        ),
    ]
