# Generated by Django 6.0.4 on 2026-05-05 09:27

import apps.organization.models.lawyer
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_real_name_nullable'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lawyer',
            managers=[
                ('objects', apps.organization.models.lawyer.LawyerManager()),
            ],
        ),
    ]
