# Generated by Django 6.0.2 on 2026-02-28 16:56

import apps.evidence.models.evidence_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidenceitem",
            name="cross_examination",
            field=models.JSONField(blank=True, default=dict, help_text="对方证据的质证意见", verbose_name="质证意见"),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("our", "我方证据"), ("opponent", "对方证据"), ("court", "法院调取")],
                max_length=20,
                verbose_name="证据方向",
            ),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="evidence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("documentary", "书证"),
                    ("physical", "物证"),
                    ("audiovisual", "视听资料"),
                    ("electronic", "电子数据"),
                    ("witness", "证人证言"),
                    ("appraisal", "鉴定意见"),
                    ("inspection", "勘验笔录"),
                    ("statement", "当事人陈述"),
                ],
                max_length=20,
                verbose_name="证据种类",
            ),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="file_hash",
            field=models.CharField(blank=True, help_text="SHA-256", max_length=64, verbose_name="文件哈希"),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="ocr_text",
            field=models.TextField(blank=True, help_text="证据文件的OCR提取文本,用于全文搜索", verbose_name="OCR文本"),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="original_location",
            field=models.CharField(blank=True, max_length=200, verbose_name="原件存放位置"),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="original_status",
            field=models.CharField(
                blank=True,
                choices=[("has_original", "有原件"), ("copy_only", "仅复印件"), ("electronic", "电子原件")],
                max_length=20,
                verbose_name="原件状态",
            ),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="source_channel",
            field=models.CharField(blank=True, max_length=50, verbose_name="来源渠道"),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="three_properties",
            field=models.JSONField(
                blank=True, default=dict, help_text="真实性/合法性/关联性说明", verbose_name="三性说明"
            ),
        ),
        migrations.AlterField(
            model_name="evidencelist",
            name="merged_pdf",
            field=models.FileField(
                blank=True,
                help_text="将所有证据文件合并为一个PDF,便于打印和提交",
                null=True,
                storage=apps.evidence.models.evidence_storage.EvidenceFileStorage(),
                upload_to="evidence/merged/%Y/%m/",
                verbose_name="合并PDF",
            ),
        ),
        migrations.AlterModelTable(
            name="evidenceitem",
            table="documents_evidenceitem",
        ),
        migrations.AlterModelTable(
            name="evidencelist",
            table="documents_evidencelist",
        ),
    ]
