# Generated by Django 6.0.2 on 2026-03-04 03:01

import apps.evidence.models.evidence_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_evidenceitem_cross_examination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidencelist",
            name="merged_pdf",
            field=models.FileField(
                blank=True,
                help_text="将所有证据文件合并为一个PDF,便于打印和提交",
                null=True,
                storage=apps.evidence.models.evidence_storage.EvidenceFileStorage(
                    base_url="/media/evidence/",
                    location="/Users/huangsong21/Downloads/Coding/AI/FachuanHybridSystem/backend/apiSystem/media/evidence",
                ),
                upload_to="evidence/merged/%Y/%m/",
                verbose_name="合并PDF",
            ),
        ),
    ]
