# Generated by Django 6.0.2 on 2026-03-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_evidencelist_merged_pdf"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="promptversion",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="promptversion",
            name="documents_p_name_55877d_idx",
        ),
        migrations.DeleteModel(
            name="PromptVersion",
        ),
    ]
