# Generated by Django 6.0.2 on 2026-03-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_promptversion_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttemplate",
            name="description",
        ),
    ]
