# Generated by Django 6.0.2 on 2026-03-23 08:38

from django.db import migrations, models


def migrate_proxy_rule_case_types(apps, schema_editor):
    ProxyMatterRule = apps.get_model("documents", "ProxyMatterRule")
    for rule in ProxyMatterRule.objects.all().only("id", "case_type", "case_types"):
        if rule.case_types:
            continue
        if rule.case_type:
            rule.case_types = [rule.case_type]
            rule.save(update_fields=["case_types"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_remove_documenttemplate_description"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="proxymatterrule",
            name="documents_p_case_ty_a13a8f_idx",
        ),
        migrations.AddField(
            model_name="proxymatterrule",
            name="case_types",
            field=models.JSONField(
                blank=True, default=list, help_text="可单选或多选;为空表示匹配任意案件类型", verbose_name="案件类型"
            ),
        ),
        migrations.RunPython(migrate_proxy_rule_case_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="proxymatterrule",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civil", "民事"),
                    ("administrative", "行政"),
                    ("criminal", "刑事"),
                    ("execution", "申请执行"),
                    ("bankruptcy", "破产"),
                ],
                help_text="兼容旧数据字段，请使用“案件类型（多选）”",
                max_length=32,
                null=True,
                verbose_name="案件类型",
            ),
        ),
        migrations.AddIndex(
            model_name="proxymatterrule",
            index=models.Index(fields=["case_stage", "is_active"], name="documents_p_case_st_e5041b_idx"),
        ),
    ]
