# Generated by Django 6.0.4 on 2026-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_remove_proxymatterrule_documents_p_case_ty_a13a8f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="archive_sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("case_cover", "案卷封面模板"),
                    ("closing_archive_register", "结案归档登记表模板"),
                    ("inner_catalog", "卷内目录模板"),
                    ("lawyer_work_log", "律师工作日志模板"),
                    ("service_quality_card", "律师办案服务质量监督卡模板"),
                    ("case_summary", "办案小结模板"),
                ],
                help_text="仅在选择'归档文件模板'时有效,可选择案卷封面、结案归档登记表等",
                max_length=50,
                null=True,
                verbose_name="归档文件子类型",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="template_type",
            field=models.CharField(
                choices=[("contract", "合同文件模板"), ("case", "案件文件模板"), ("archive", "归档文件模板")],
                default="contract",
                help_text="选择此模板用于合同还是案件",
                max_length=20,
                verbose_name="模板类型",
            ),
        ),
    ]
