# Generated by Django 6.0.2 on 2026-02-27 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("original_file", models.CharField(max_length=512, verbose_name="原始文件路径")),
                ("output_file", models.CharField(blank=True, max_length=512, verbose_name="输出文件路径")),
                ("contract_title", models.CharField(blank=True, max_length=256, verbose_name="合同标题")),
                ("party_a", models.CharField(blank=True, max_length=256, verbose_name="甲方")),
                ("party_b", models.CharField(blank=True, max_length=256, verbose_name="乙方")),
                (
                    "represented_party",
                    models.CharField(
                        blank=True,
                        choices=[("party_a", "甲方"), ("party_b", "乙方")],
                        max_length=16,
                        verbose_name="用户代表方",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "已上传"),
                            ("parties_identified", "已识别当事人"),
                            ("confirmed", "已确认"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("extraction_failed", "提取失败"),
                        ],
                        default="uploaded",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("title_extraction", "标题提取"),
                            ("typo_check", "错别字检测"),
                            ("contract_review", "合同审查"),
                            ("page_numbering", "页码标准化"),
                            ("heading_numbering", "标题序号"),
                        ],
                        max_length=32,
                        verbose_name="当前处理步骤",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("model_name", models.CharField(blank=True, max_length=128, verbose_name="LLM 模型名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "合同审查任务",
                "verbose_name_plural": "合同审查任务",
            },
        ),
    ]
