# Generated by Django 6.0.2 on 2026-02-27 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contract_review", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewtask",
            index=models.Index(fields=["user", "-created_at"], name="contract_re_user_id_7794c2_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewtask",
            index=models.Index(fields=["status", "-created_at"], name="contract_re_status_bcb346_idx"),
        ),
    ]
