# Generated by Django 6.0.2 on 2026-02-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="party_c",
            field=models.CharField(blank=True, max_length=256, verbose_name="丙方"),
        ),
        migrations.AddField(
            model_name="reviewtask",
            name="party_d",
            field=models.CharField(blank=True, max_length=256, verbose_name="丁方"),
        ),
        migrations.AlterField(
            model_name="reviewtask",
            name="represented_party",
            field=models.CharField(
                blank=True,
                choices=[("party_a", "甲方"), ("party_b", "乙方"), ("party_c", "丙方"), ("party_d", "丁方")],
                max_length=16,
                verbose_name="用户代表方",
            ),
        ),
    ]
