# Generated by Django 6.0.2 on 2026-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0003_reviewtask_party_c_reviewtask_party_d_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewtask",
            name="current_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("title_extraction", "标题提取"),
                    ("typo_check", "错别字检测"),
                    ("contract_review", "合同审查"),
                    ("format_document", "格式标准化"),
                    ("page_numbering", "页码标准化"),
                    ("heading_numbering", "标题序号"),
                ],
                max_length=32,
                verbose_name="当前处理步骤",
            ),
        ),
    ]
