# Generated by Django 6.0.2 on 2026-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0004_alter_reviewtask_current_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="reviewer_name",
            field=models.CharField(blank=True, default="法穿AI", max_length=128, verbose_name="修订人名称"),
        ),
    ]
