# Generated by Django 6.0.2 on 2026-02-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0005_reviewtask_reviewer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="review_report",
            field=models.TextField(blank=True, verbose_name="评估报告"),
        ),
    ]
