# Generated by Django 6.0.2 on 2026-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0006_reviewtask_review_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="selected_steps",
            field=models.JSONField(
                blank=True, default=list, help_text="用户选择执行的步骤列表", verbose_name="选中的处理步骤"
            ),
        ),
    ]
