# Generated by Django 6.0.2 on 2026-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0007_add_selected_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="custom_api_key",
            field=models.CharField(blank=True, max_length=256, verbose_name="自定义 API Key"),
        ),
        migrations.AddField(
            model_name="reviewtask",
            name="custom_base_url",
            field=models.CharField(blank=True, max_length=512, verbose_name="自定义 API 地址"),
        ),
    ]
