# Generated by Django 6.0.2 on 2026-02-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0008_add_custom_llm_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="运行时长（秒）"),
        ),
    ]
