# Generated by Django 6.0.2 on 2026-02-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0009_add_duration_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewtask",
            name="custom_api_key",
        ),
        migrations.RemoveField(
            model_name="reviewtask",
            name="custom_base_url",
        ),
        migrations.RemoveField(
            model_name="reviewtask",
            name="duration_seconds",
        ),
    ]
