# Generated by Django 6.0.2 on 2026-03-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_review", "0010_remove_reviewtask_custom_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="pdf_cache_file",
            field=models.CharField(blank=True, max_length=512, verbose_name="PDF 缓存文件路径"),
        ),
    ]
