# Generated by Django 6.0.4 on 2026-04-16 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchPrintingTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Batch Printing", max_length=64)),
            ],
            options={
                "verbose_name": "批量打印",
                "verbose_name_plural": "批量打印",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BatchPrintJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("partial_failed", "部分失败"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0, verbose_name="总文件数")),
                ("processed_count", models.PositiveIntegerField(default=0, verbose_name="已处理数量")),
                ("success_count", models.PositiveIntegerField(default=0, verbose_name="成功数量")),
                ("failed_count", models.PositiveIntegerField(default=0, verbose_name="失败数量")),
                ("progress", models.PositiveIntegerField(default=0, verbose_name="进度")),
                ("task_id", models.CharField(blank=True, default="", max_length=64, verbose_name="任务ID")),
                ("cancel_requested", models.BooleanField(default=False, verbose_name="请求取消")),
                ("capability_payload", models.JSONField(blank=True, default=dict, verbose_name="能力快照")),
                ("summary_payload", models.JSONField(blank=True, default=dict, verbose_name="任务摘要")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_print_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "批量打印任务",
                "verbose_name_plural": "批量打印任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintPresetSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("printer_name", models.CharField(max_length=255, verbose_name="打印机名称")),
                (
                    "printer_display_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="打印机展示名称"),
                ),
                ("preset_name", models.CharField(max_length=255, verbose_name="预置名称")),
                ("preset_source", models.CharField(blank=True, default="", max_length=255, verbose_name="预置来源")),
                ("raw_settings_payload", models.JSONField(blank=True, default=dict, verbose_name="原始设置")),
                (
                    "executable_options_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="可执行打印参数"),
                ),
                ("supported_option_names", models.JSONField(blank=True, default=list, verbose_name="驱动支持参数名")),
                ("last_synced_at", models.DateTimeField(verbose_name="最近同步时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "打印预置快照",
                "verbose_name_plural": "打印预置快照",
                "ordering": ["printer_name", "preset_name", "-updated_at"],
                "indexes": [
                    models.Index(fields=["printer_name", "preset_name"], name="batch_print_printer_99eeb3_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("printer_name", "preset_name"), name="batch_printing_preset_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="PrintKeywordRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keyword", models.CharField(max_length=255, verbose_name="关键词")),
                ("priority", models.PositiveIntegerField(default=100, verbose_name="优先级")),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                ("printer_name", models.CharField(max_length=255, verbose_name="目标打印机")),
                ("notes", models.CharField(blank=True, default="", max_length=255, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "preset_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="batch_printing.printpresetsnapshot",
                        verbose_name="目标预置",
                    ),
                ),
            ],
            options={
                "verbose_name": "关键词打印规则",
                "verbose_name_plural": "关键词打印规则",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="BatchPrintItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="排序")),
                ("source_original_name", models.CharField(max_length=255, verbose_name="原始文件名")),
                ("source_relpath", models.CharField(max_length=1024, verbose_name="源文件相对路径")),
                (
                    "prepared_relpath",
                    models.CharField(blank=True, default="", max_length=1024, verbose_name="打印文件相对路径"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX")], max_length=16, verbose_name="文件类型"
                    ),
                ),
                (
                    "matched_keyword",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="命中关键词"),
                ),
                (
                    "target_printer_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="目标打印机"),
                ),
                (
                    "target_preset_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="目标预置名称"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("cups_job_id", models.CharField(blank=True, default="", max_length=64, verbose_name="CUPS 任务ID")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="batch_printing.batchprintjob",
                        verbose_name="批次任务",
                    ),
                ),
                (
                    "matched_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_items",
                        to="batch_printing.printkeywordrule",
                        verbose_name="命中规则",
                    ),
                ),
                (
                    "target_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_items",
                        to="batch_printing.printpresetsnapshot",
                        verbose_name="目标预置",
                    ),
                ),
            ],
            options={
                "verbose_name": "批量打印明细",
                "verbose_name_plural": "批量打印明细",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="batchprintjob",
            index=models.Index(fields=["status", "-created_at"], name="batch_print_status_ba4ebd_idx"),
        ),
        migrations.AddIndex(
            model_name="batchprintjob",
            index=models.Index(fields=["created_by", "-created_at"], name="batch_print_created_5d6f41_idx"),
        ),
        migrations.AddIndex(
            model_name="printkeywordrule",
            index=models.Index(fields=["enabled", "priority"], name="batch_print_enabled_707726_idx"),
        ),
        migrations.AddIndex(
            model_name="batchprintitem",
            index=models.Index(fields=["job", "status"], name="batch_print_job_id_641f7e_idx"),
        ),
        migrations.AddIndex(
            model_name="batchprintitem",
            index=models.Index(fields=["target_printer_name", "status"], name="batch_print_target__8df7b6_idx"),
        ),
        migrations.AddConstraint(
            model_name="batchprintitem",
            constraint=models.UniqueConstraint(fields=("job", "order"), name="batch_printing_item_job_order_unique"),
        ),
    ]
