# Generated by Django 6.0.2 on 2026-02-28 06:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="合同名称")),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("civil", "民商事"),
                            ("criminal", "刑事"),
                            ("administrative", "行政"),
                            ("labor", "劳动仲裁"),
                            ("intl", "商事仲裁"),
                            ("special", "专项服务"),
                            ("advisor", "常法顾问"),
                        ],
                        max_length=32,
                        verbose_name="合同类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "在办"), ("closed", "已结案")],
                        default="active",
                        max_length=32,
                        verbose_name="合同状态",
                    ),
                ),
                ("specified_date", models.DateField(default=django.utils.timezone.localdate, verbose_name="指定日期")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="开始日期")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="结束日期")),
                ("is_archived", models.BooleanField(default=False, verbose_name="是否已建档")),
                (
                    "filing_number",
                    models.CharField(
                        blank=True,
                        help_text="格式: {年份}_{合同类型}_{HT}_{序号}",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="建档编号",
                    ),
                ),
                (
                    "fee_mode",
                    models.CharField(
                        choices=[
                            ("FIXED", "固定收费"),
                            ("SEMI_RISK", "半风险收费"),
                            ("FULL_RISK", "全风险收费"),
                            ("CUSTOM", "自定义"),
                        ],
                        default="FIXED",
                        max_length=16,
                        verbose_name="收费模式",
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="固定/前期律师费"
                    ),
                ),
                (
                    "risk_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="风险比例(%)"
                    ),
                ),
                ("custom_terms", models.TextField(blank=True, null=True, verbose_name="自定义收费条款")),
                ("representation_stages", models.JSONField(blank=True, default=list, verbose_name="代理阶段")),
            ],
            options={
                "verbose_name": "合同",
                "verbose_name_plural": "合同",
                "indexes": [
                    models.Index(fields=["case_type"], name="contracts_c_case_ty_14804d_idx"),
                    models.Index(fields=["status"], name="contracts_c_status_aa7a80_idx"),
                    models.Index(fields=["is_archived"], name="contracts_c_is_arch_1df554_idx"),
                    models.Index(fields=["specified_date"], name="contracts_c_specifi_efa563_idx"),
                    models.Index(fields=["-specified_date"], name="contracts_c_specifi_9bfb37_idx"),
                    models.Index(fields=["filing_number"], name="contracts_c_filing__706b73_idx"),
                    models.Index(fields=["case_type", "status"], name="contracts_c_case_ty_6edb9b_idx"),
                    models.Index(fields=["status", "-specified_date"], name="contracts_c_status_5d1a4a_idx"),
                    models.Index(fields=["is_archived", "-specified_date"], name="contracts_c_is_arch_4b81ea_idx"),
                    models.Index(
                        fields=["case_type", "status", "-specified_date"], name="contracts_c_case_ty_d0bea9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="收款金额")),
                ("received_at", models.DateField(default=django.utils.timezone.localdate, verbose_name="收款日期")),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("UNINVOICED", "未开票"),
                            ("INVOICED_PARTIAL", "部分开票"),
                            ("INVOICED_FULL", "已开票"),
                        ],
                        default="UNINVOICED",
                        max_length=32,
                        verbose_name="开票状态",
                    ),
                ),
                (
                    "invoiced_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="已开票金额"),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同收款",
                "verbose_name_plural": "合同收款",
            },
        ),
        migrations.CreateModel(
            name="FinalizedMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("original_filename", models.CharField(max_length=255, verbose_name="原始文件名")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("contract_original", "合同正本"),
                            ("supplementary_agreement", "补充协议"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="材料分类",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finalized_materials",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "定稿材料",
                "verbose_name_plural": "定稿材料",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("original_filename", models.CharField(max_length=255, verbose_name="原始文件名")),
                ("remark", models.TextField(blank=True, default="", verbose_name="备注")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                ("invoice_code", models.CharField(blank=True, default="", max_length=20, verbose_name="发票代码")),
                ("invoice_number", models.CharField(blank=True, default="", max_length=20, verbose_name="发票号码")),
                ("invoice_date", models.DateField(blank=True, null=True, verbose_name="开票日期")),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="金额"),
                ),
                (
                    "tax_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="税额"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="价税合计"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="contracts.contractpayment",
                        verbose_name="收款记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票",
                "verbose_name_plural": "发票",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplementaryAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True, verbose_name="补充协议名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplementary_agreements",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "补充协议",
                "verbose_name_plural": "补充协议",
            },
        ),
        migrations.CreateModel(
            name="SupplementaryAgreementParty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("PRINCIPAL", "委托人"), ("BENEFICIARY", "受益人"), ("OPPOSING", "对方当事人")],
                        default="PRINCIPAL",
                        max_length=16,
                        verbose_name="身份",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplementary_agreements",
                        to="client.client",
                        verbose_name="当事人",
                    ),
                ),
                (
                    "supplementary_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="contracts.supplementaryagreement",
                        verbose_name="补充协议",
                    ),
                ),
            ],
            options={
                "verbose_name": "补充协议当事人",
                "verbose_name_plural": "补充协议当事人",
            },
        ),
        migrations.CreateModel(
            name="ClientPaymentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="回款金额")),
                ("image_path", models.CharField(blank=True, max_length=500, null=True, verbose_name="凭证图片路径")),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_payment_records",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_payment_records",
                        to="contracts.contract",
                        verbose_name="关联合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户回款",
                "verbose_name_plural": "客户回款",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["contract"], name="contracts_c_contrac_91115c_idx"),
                    models.Index(fields=["-created_at"], name="contracts_c_created_08e278_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_primary", models.BooleanField(default=False, verbose_name="是否主办律师")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="律师",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同指派",
                "verbose_name_plural": "合同指派",
                "ordering": ["-is_primary", "order"],
                "unique_together": {("contract", "lawyer")},
            },
        ),
        migrations.CreateModel(
            name="ContractFinanceLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=64, verbose_name="动作")),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "信息"), ("WARN", "预警"), ("ERROR", "错误")],
                        default="INFO",
                        max_length=16,
                        verbose_name="级别",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="数据")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_logs",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "财务日志",
                "verbose_name_plural": "财务日志",
                "indexes": [
                    models.Index(fields=["contract", "created_at"], name="contracts_c_contrac_cfcd0d_idx"),
                    models.Index(fields=["level"], name="contracts_c_level_76f463_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractFolderBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "folder_path",
                    models.CharField(
                        help_text="绑定的本地或网络文件夹路径", max_length=1000, verbose_name="文件夹路径"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="绑定时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_binding",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同文件夹绑定",
                "verbose_name_plural": "合同文件夹绑定",
                "indexes": [
                    models.Index(fields=["contract"], name="contracts_c_contrac_892d47_idx"),
                    models.Index(fields=["-created_at"], name="contracts_c_created_beefcb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractParty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("PRINCIPAL", "委托人"), ("BENEFICIARY", "受益人"), ("OPPOSING", "对方当事人")],
                        default="PRINCIPAL",
                        max_length=16,
                        verbose_name="身份",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="client.client",
                        verbose_name="当事人",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_parties",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同当事人",
                "verbose_name_plural": "合同当事人",
                "unique_together": {("contract", "client")},
            },
        ),
        migrations.AddIndex(
            model_name="contractpayment",
            index=models.Index(fields=["contract", "received_at"], name="contracts_c_contrac_6782a0_idx"),
        ),
        migrations.AddIndex(
            model_name="contractpayment",
            index=models.Index(fields=["invoice_status"], name="contracts_c_invoice_fc503d_idx"),
        ),
        migrations.AddIndex(
            model_name="finalizedmaterial",
            index=models.Index(fields=["contract", "-uploaded_at"], name="contracts_f_contrac_4d4af4_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["payment", "-uploaded_at"], name="contracts_i_payment_3af6ef_idx"),
        ),
        migrations.AddIndex(
            model_name="supplementaryagreement",
            index=models.Index(fields=["contract", "-created_at"], name="contracts_s_contrac_ce9f0e_idx"),
        ),
        migrations.AddIndex(
            model_name="supplementaryagreement",
            index=models.Index(fields=["-created_at"], name="contracts_s_created_9b1c28_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="supplementaryagreementparty",
            unique_together={("supplementary_agreement", "client")},
        ),
    ]
