# Generated by Django 6.0.2 on 2026-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finalizedmaterial",
            options={
                "ordering": ["order", "-uploaded_at"],
                "verbose_name": "定稿材料",
                "verbose_name_plural": "定稿材料",
            },
        ),
        migrations.RemoveIndex(
            model_name="finalizedmaterial",
            name="contracts_f_contrac_4d4af4_idx",
        ),
        migrations.AddField(
            model_name="finalizedmaterial",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AddIndex(
            model_name="finalizedmaterial",
            index=models.Index(fields=["contract", "order", "-uploaded_at"], name="contracts_f_contrac_840bc7_idx"),
        ),
    ]
