# Generated by Django 6.0.2 on 2026-03-19 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_add_order_to_finalized_material"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractFolderScanSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "扫描中"),
                            ("classifying", "分类中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("imported", "已导入"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("task_id", models.CharField(blank=True, default="", max_length=64, verbose_name="DjangoQ任务ID")),
                ("progress", models.PositiveIntegerField(default=0, verbose_name="进度百分比")),
                ("current_file", models.CharField(blank=True, default="", max_length=255, verbose_name="当前文件")),
                ("result_payload", models.JSONField(blank=True, default=dict, verbose_name="结果载荷")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_scan_sessions",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_folder_scan_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同文件夹扫描会话",
                "verbose_name_plural": "合同文件夹扫描会话",
                "indexes": [
                    models.Index(fields=["contract", "-created_at"], name="contracts_c_contrac_ae496b_idx"),
                    models.Index(fields=["status", "-created_at"], name="contracts_c_status_a691df_idx"),
                ],
            },
        ),
    ]
