# Generated by Django 6.0.2 on 2026-03-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_add_law_firm_oa_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="law_firm_oa_case_number",
            field=models.CharField(
                blank=True, help_text="律所OA系统中的案件编号", max_length=100, null=True, verbose_name="律所OA案件编号"
            ),
        ),
    ]
