# Generated by Django 6.0.3 on 2026-04-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_contractoasyncsession"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contractoasyncsession",
            new_name="contracts_c_status_f0471f_idx",
            old_name="contracts_c_status_3c4e2f_idx",
        ),
        migrations.RenameIndex(
            model_name="contractoasyncsession",
            new_name="contracts_c_started_8bb64f_idx",
            old_name="contracts_c_started_72dffa_idx",
        ),
    ]
