# Generated by Django 6.0.3 on 2026-04-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_rename_contracts_c_status_3c4e2f_idx_contracts_c_status_f0471f_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finalizedmaterial",
            options={
                "ordering": ["order", "-uploaded_at"],
                "verbose_name": "归档材料",
                "verbose_name_plural": "归档材料",
            },
        ),
    ]
