# Generated by Django 6.0.3 on 2026-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_alter_finalizedmaterial_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[("active", "在办"), ("closed", "已结案"), ("archived", "已归档")],
                default="active",
                max_length=32,
                verbose_name="合同状态",
            ),
        ),
    ]
