# Generated by Django 6.0.4 on 2026-04-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_remove_caselog_cases_casel_case_id_81df24_idx_and_more'),
        ('contracts', '0011_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='log_anchor_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_log_anchor', to='cases.case', verbose_name='日志中心案件'),
        ),
    ]
