# Generated by Django 6.0.4 on 2026-04-22 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contract_log_anchor_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedmaterial',
            name='source_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalized_material', to='contracts.invoice', verbose_name='来源发票'),
        ),
    ]
