# Generated by Django 6.0.4 on 2026-04-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0013_finalizedmaterial_archive_item_code"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contract",
            name="contracts_c_is_arch_1df554_idx",
        ),
        migrations.RemoveIndex(
            model_name="contract",
            name="contracts_c_is_arch_4b81ea_idx",
        ),
        migrations.AlterField(
            model_name="finalizedmaterial",
            name="category",
            field=models.CharField(
                choices=[
                    ("contract_original", "合同正本"),
                    ("supplementary_agreement", "补充协议"),
                    ("invoice", "发票"),
                    ("archive_document", "归档文书"),
                    ("supervision_card", "监督卡"),
                ],
                default="invoice",
                max_length=32,
                verbose_name="材料分类",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["is_filed"], name="contracts_c_is_file_b7e9f8_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["is_filed", "-specified_date"], name="contracts_c_is_file_86efbd_idx"),
        ),
    ]
