# Generated by Django 6.0.4 on 2026-04-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_migrate_archive_item_code_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedmaterial',
            name='archive_item_code',
            field=models.CharField(blank=True, default='', help_text="关联归档检查清单的标识符，如 'nl_1'、'lt_6'", max_length=20, verbose_name='归档清单编号'),
        ),
    ]
