# Generated by Django 6.0.4 on 2026-04-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0017_add_case_material_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivePlaceholderOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "template_subtype",
                    models.CharField(
                        help_text="DocumentArchiveSubType 值，如 case_cover、closing_archive_register",
                        max_length=50,
                        verbose_name="归档模板子类型",
                    ),
                ),
                (
                    "overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用户手动覆盖的占位符键值对，如 {'主办律师姓名': '张三'}",
                        verbose_name="覆盖值",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_overrides",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "归档占位符覆盖",
                "verbose_name_plural": "归档占位符覆盖",
                "indexes": [
                    models.Index(fields=["contract", "template_subtype"], name="contracts_a_contrac_848705_idx")
                ],
                "unique_together": {("contract", "template_subtype")},
            },
        ),
    ]
