# Generated by Django 6.0.4 on 2026-04-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0018_archive_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="compact_archive",
            field=models.BooleanField(
                default=False,
                help_text="开启后，归档检查清单仅显示有材料的项，未上传材料的项目不纳入归档范围",
                verbose_name="按实归档",
            ),
        ),
    ]
