# Generated by Django 6.0.4 on 2026-04-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0019_add_compact_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractfolderbinding",
            name="folder_device",
            field=models.IntegerField(
                blank=True, help_text="文件夹所在设备号，与 inode 配合使用", null=True, verbose_name="设备号"
            ),
        ),
        migrations.AddField(
            model_name="contractfolderbinding",
            name="folder_inode",
            field=models.BigIntegerField(
                blank=True, help_text="文件夹 inode 编号，用于路径自动修复", null=True, verbose_name="inode"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="compact_archive",
            field=models.BooleanField(
                default=False,
                help_text="开启后，归档检查清单仅显示有材料的项，未上传材料的项目不纳入归档范围",
                verbose_name="精简视图",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[("unsigned", "未签约"), ("active", "在办"), ("closed", "已结案"), ("archived", "已归档")],
                default="active",
                max_length=32,
                verbose_name="合同状态",
            ),
        ),
    ]
