# Generated by Django 6.0.4 on 2026-04-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0021_alter_finalizedmaterial_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalizedmaterial",
            name="category",
            field=models.CharField(
                choices=[
                    ("contract_original", "合同正本"),
                    ("supplementary_agreement", "补充协议"),
                    ("invoice", "发票"),
                    ("archive_document", "归档文书"),
                    ("supervision_card", "监督卡"),
                    ("authorization_material", "授权委托材料"),
                    ("case_material", "案件材料同步"),
                    ("archive_upload", "归档上传"),
                ],
                default="archive_document",
                max_length=32,
                verbose_name="材料分类",
            ),
        ),
    ]
