# Generated by Django 6.0.4 on 2026-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contractpayment_case'),
        ('contracts', '0023_remove_closed_status'),
    ]

    operations = [
    ]
