# Generated by Django 6.0.4 on 2026-04-25 07:18

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_historical_records"),
        ("contracts", "0023_remove_closed_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalClientPaymentRecord",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="回款金额")),
                ("image_path", models.CharField(blank=True, max_length=500, null=True, verbose_name="凭证图片路径")),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(blank=True, editable=False, verbose_name="创建时间")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contracts.contract",
                        verbose_name="关联合同",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 客户回款",
                "verbose_name_plural": "historical 客户回款",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="合同名称")),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("civil", "民商事"),
                            ("criminal", "刑事"),
                            ("administrative", "行政"),
                            ("labor", "劳动仲裁"),
                            ("intl", "商事仲裁"),
                            ("special", "专项服务"),
                            ("advisor", "常法顾问"),
                        ],
                        max_length=32,
                        verbose_name="合同类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("unsigned", "未签约"), ("active", "在办"), ("archived", "已归档")],
                        default="active",
                        max_length=32,
                        verbose_name="合同状态",
                    ),
                ),
                ("specified_date", models.DateField(default=django.utils.timezone.localdate, verbose_name="指定日期")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="开始日期")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="结束日期")),
                ("is_filed", models.BooleanField(default=False, verbose_name="是否已建档")),
                (
                    "filing_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="格式: {年份}_{合同类型}_{HT}_{序号}",
                        max_length=50,
                        null=True,
                        verbose_name="建档编号",
                    ),
                ),
                (
                    "fee_mode",
                    models.CharField(
                        choices=[
                            ("FIXED", "固定收费"),
                            ("SEMI_RISK", "半风险收费"),
                            ("FULL_RISK", "全风险收费"),
                            ("CUSTOM", "自定义"),
                        ],
                        default="FIXED",
                        max_length=16,
                        verbose_name="收费模式",
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="固定/前期律师费"
                    ),
                ),
                (
                    "risk_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="风险比例(%)"
                    ),
                ),
                ("custom_terms", models.TextField(blank=True, null=True, verbose_name="自定义收费条款")),
                (
                    "law_firm_oa_url",
                    models.URLField(
                        blank=True,
                        help_text="跳转至律所OA系统中该合同的页面",
                        max_length=500,
                        null=True,
                        verbose_name="律所OA链接",
                    ),
                ),
                (
                    "law_firm_oa_case_number",
                    models.CharField(
                        blank=True,
                        help_text="律所OA系统中的案件编号",
                        max_length=100,
                        null=True,
                        verbose_name="律所OA案件编号",
                    ),
                ),
                ("representation_stages", models.JSONField(blank=True, default=list, verbose_name="代理阶段")),
                (
                    "compact_archive",
                    models.BooleanField(
                        default=False,
                        help_text="开启后，归档检查清单仅显示有材料的项，未上传材料的项目不纳入归档范围",
                        verbose_name="精简视图",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 合同",
                "verbose_name_plural": "historical 合同",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContractPayment",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="收款金额")),
                ("received_at", models.DateField(default=django.utils.timezone.localdate, verbose_name="收款日期")),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("UNINVOICED", "未开票"),
                            ("INVOICED_PARTIAL", "部分开票"),
                            ("INVOICED_FULL", "已开票"),
                        ],
                        default="UNINVOICED",
                        max_length=32,
                        verbose_name="开票状态",
                    ),
                ),
                (
                    "invoiced_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="已开票金额"),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(blank=True, editable=False, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(blank=True, editable=False, verbose_name="更新时间")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contracts.contract",
                        verbose_name="合同",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 合同收款",
                "verbose_name_plural": "historical 合同收款",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
