# Generated by Django 6.0.4 on 2026-04-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0024_historical_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalizedmaterial",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256, 用于去重",
                max_length=64,
                verbose_name="内容哈希",
            ),
        ),
        migrations.CreateModel(
            name="ArchiveClassificationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "archive_category",
                    models.CharField(
                        help_text="non_litigation / litigation / criminal", max_length=32, verbose_name="归档分类"
                    ),
                ),
                (
                    "filename_keyword",
                    models.CharField(help_text="从文件名中提取的关键词", max_length=100, verbose_name="文件名关键词"),
                ),
                (
                    "archive_item_code",
                    models.CharField(
                        help_text="目标归档清单项编号，如 'lt_7'、'cr_14'", max_length=20, verbose_name="归档清单编号"
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(default=1, help_text="学习到该规则的次数", verbose_name="命中次数"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("learned", "自动学习"), ("manual", "手动添加")],
                        default="learned",
                        max_length=10,
                        verbose_name="规则来源",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "归档分类学习规则",
                "verbose_name_plural": "归档分类学习规则",
                "indexes": [
                    models.Index(fields=["archive_category", "filename_keyword"], name="contracts_a_archive_5caba9_idx")
                ],
                "unique_together": {("archive_category", "filename_keyword")},
            },
        ),
    ]
