# Generated by Django 6.0.4 on 2026-05-08

from __future__ import annotations

from django.db import migrations, models


def backfill_finalized_material_storage_fields(apps, schema_editor):
    FinalizedMaterial = apps.get_model("contracts", "FinalizedMaterial")
    for material in FinalizedMaterial.objects.all().only("id", "file_path", "relative_file_path", "subdir_path", "storage_root_type"):
        file_path = (material.file_path or "").replace("\\", "/").strip()
        if not file_path:
            continue

        relative_file_path = material.relative_file_path or file_path
        subdir_path = material.subdir_path or ""
        if not subdir_path and "/" in relative_file_path:
            subdir_path = relative_file_path.rsplit("/", 1)[0]

        updates = []
        if material.storage_root_type != "media":
            material.storage_root_type = "media"
            updates.append("storage_root_type")
        if material.relative_file_path != relative_file_path:
            material.relative_file_path = relative_file_path
            updates.append("relative_file_path")
        if material.subdir_path != subdir_path:
            material.subdir_path = subdir_path
            updates.append("subdir_path")

        if updates:
            material.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0028_p3_protect_payment_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalizedmaterial",
            name="relative_file_path",
            field=models.CharField(blank=True, db_index=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="finalizedmaterial",
            name="storage_root_type",
            field=models.CharField(blank=True, default="media", max_length=32),
        ),
        migrations.AddField(
            model_name="finalizedmaterial",
            name="subdir_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.RunPython(backfill_finalized_material_storage_fields, migrations.RunPython.noop),
    ]
