# Generated by Django 6.0.4 on 2026-05-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_finalizedmaterial_storage_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedmaterial',
            name='archive_item_code',
            field=models.CharField(blank=True, default='', help_text="关联归档检查清单的标识符，例如 'nl_1'、'lt_6'", max_length=20, verbose_name='归档清单编号'),
        ),
        migrations.AlterField(
            model_name='finalizedmaterial',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256，用于去重', max_length=64, verbose_name='内容哈希'),
        ),
    ]
