# Generated by Django 6.0.2 on 2026-02-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LPRRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("effective_date", models.DateField(unique=True, verbose_name="生效日期")),
                ("rate_1y", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="一年期LPR(%)")),
                ("rate_5y", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="五年期LPR(%)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "LPR利率",
                "verbose_name_plural": "LPR利率",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(verbose_name="还款日期")),
                ("payment_amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="还款金额")),
                (
                    "offset_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="冲抵费用"),
                ),
                (
                    "offset_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="冲抵利息"),
                ),
                (
                    "offset_principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="冲抵本金"),
                ),
                ("remaining_principal", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="剩余本金")),
                ("remarks", models.TextField(blank=True, default="", verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_payments",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "还款冲抵记录",
                "verbose_name_plural": "还款冲抵记录",
                "ordering": ["payment_date"],
            },
        ),
    ]
