# Generated by Django 6.0.2 on 2026-02-28 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_initial"),
        ("sales_dispute", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contract_basis",
                    models.CharField(
                        choices=[("written", "书面合同"), ("oral", "口头约定"), ("trade_custom", "交易习惯")],
                        max_length=32,
                        verbose_name="合同基础类型",
                    ),
                ),
                ("principal_amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="债权本金")),
                (
                    "evidence_total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="证据完整度总分"),
                ),
                (
                    "limitation_status",
                    models.CharField(
                        choices=[("normal", "正常"), ("expiring_soon", "即将届满"), ("expired", "已届满")],
                        default="normal",
                        max_length=32,
                        verbose_name="诉讼时效状态",
                    ),
                ),
                ("limitation_expiry_date", models.DateField(blank=True, null=True, verbose_name="时效届满日期")),
                (
                    "solvency_rating",
                    models.CharField(
                        choices=[("good", "良好"), ("fair", "一般"), ("poor", "较差"), ("unknown", "未知")],
                        default="unknown",
                        max_length=32,
                        verbose_name="偿付能力评级",
                    ),
                ),
                (
                    "assessment_grade",
                    models.CharField(
                        choices=[
                            ("sufficient", "充分"),
                            ("fairly_sufficient", "较充分"),
                            ("average", "一般"),
                            ("weak", "薄弱"),
                            ("severely_insufficient", "严重不足"),
                        ],
                        max_length=32,
                        verbose_name="综合评估等级",
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="", verbose_name="评估备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_dispute_assessment",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件评估记录",
                "verbose_name_plural": "案件评估记录",
            },
        ),
        migrations.CreateModel(
            name="EvidenceScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("written_contract", "书面合同"),
                            ("delivery_receipt", "送货/收货凭证"),
                            ("reconciliation", "对账确认"),
                            ("collection_record", "催款记录"),
                            ("payment_record", "付款记录"),
                        ],
                        max_length=32,
                        verbose_name="证据类型",
                    ),
                ),
                ("has_evidence", models.BooleanField(default=False, verbose_name="是否具备")),
                ("quality_score", models.IntegerField(default=0, verbose_name="证据质量评分")),
                ("remarks", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_scores",
                        to="sales_dispute.caseassessment",
                        verbose_name="关联评估记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "证据评分明细",
                "verbose_name_plural": "证据评分明细",
            },
        ),
        migrations.CreateModel(
            name="JurisdictionAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("has_agreed_jurisdiction", models.BooleanField(default=False, verbose_name="是否有约定管辖")),
                ("agreed_court", models.CharField(blank=True, default="", max_length=255, verbose_name="约定管辖法院")),
                ("is_agreed_valid", models.BooleanField(blank=True, null=True, verbose_name="约定管辖是否有效")),
                (
                    "invalid_reason",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="约定无效原因"),
                ),
                ("plaintiff_location", models.CharField(max_length=255, verbose_name="原告所在地")),
                ("defendant_location", models.CharField(max_length=255, verbose_name="被告住所地")),
                ("recommended_court", models.CharField(max_length=255, verbose_name="推荐管辖法院")),
                ("recommendation_reason", models.TextField(verbose_name="推荐理由")),
                (
                    "alternative_court",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="备选管辖法院"),
                ),
                ("legal_basis", models.TextField(verbose_name="法律依据")),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurisdiction_analysis",
                        to="sales_dispute.caseassessment",
                        verbose_name="关联评估记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "管辖权分析",
                "verbose_name_plural": "管辖权分析",
            },
        ),
        migrations.CreateModel(
            name="LitigationStrategy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("payment_order", "支付令"),
                            ("small_claims", "小额诉讼"),
                            ("summary_procedure", "简易程序"),
                            ("ordinary_procedure", "普通程序"),
                            ("pre_litigation_mediation", "诉前调解"),
                        ],
                        max_length=32,
                        verbose_name="推荐策略类型",
                    ),
                ),
                ("recommendation_reason", models.TextField(verbose_name="推荐理由")),
                ("estimated_duration", models.CharField(max_length=64, verbose_name="预计周期")),
                ("applicable_conditions", models.TextField(verbose_name="适用条件说明")),
                ("suggest_preservation", models.BooleanField(default=False, verbose_name="是否建议财产保全")),
                ("preservation_reason", models.TextField(blank=True, default="", verbose_name="保全建议理由")),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litigation_strategy",
                        to="sales_dispute.caseassessment",
                        verbose_name="关联评估记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "起诉策略推荐",
                "verbose_name_plural": "起诉策略推荐",
            },
        ),
        migrations.AddIndex(
            model_name="caseassessment",
            index=models.Index(fields=["assessment_grade"], name="sales_dispu_assessm_e867ff_idx"),
        ),
        migrations.AddIndex(
            model_name="caseassessment",
            index=models.Index(fields=["limitation_status"], name="sales_dispu_limitat_cc16a5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="evidencescore",
            unique_together={("assessment", "evidence_type")},
        ),
    ]
