# Generated by Django 6.0.2 on 2026-02-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_initial"),
        ("sales_dispute", "0002_caseassessment_evidencescore_jurisdictionanalysis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("phone_collection", "电话催款"),
                            ("written_collection", "书面催款"),
                            ("lawyer_letter", "律师函"),
                            ("ultimatum", "最后通牒"),
                            ("litigation", "起诉"),
                        ],
                        default="phone_collection",
                        max_length=32,
                        verbose_name="当前催收阶段",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="催收启动日期")),
                ("last_action_date", models.DateField(blank=True, null=True, verbose_name="最近操作日期")),
                ("next_due_date", models.DateField(blank=True, null=True, verbose_name="下一节点到期日")),
                ("remarks", models.TextField(blank=True, default="", verbose_name="催收备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_record",
                        to="cases.case",
                        verbose_name="关联案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "催收记录",
                "verbose_name_plural": "催收记录",
            },
        ),
        migrations.CreateModel(
            name="CollectionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("phone_collection", "电话催款"),
                            ("written_collection", "书面催款"),
                            ("lawyer_letter", "律师函"),
                            ("ultimatum", "最后通牒"),
                            ("litigation", "起诉"),
                        ],
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                ("action_date", models.DateField(verbose_name="操作日期")),
                ("description", models.TextField(verbose_name="操作描述")),
                ("document_type", models.CharField(blank=True, default="", max_length=64, verbose_name="文书类型")),
                (
                    "document_filename",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="文书文件名"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="sales_dispute.collectionrecord",
                        verbose_name="关联催收记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "催收操作日志",
                "verbose_name_plural": "催收操作日志",
                "ordering": ["-action_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="collectionrecord",
            index=models.Index(fields=["current_stage"], name="sales_dispu_current_c416ab_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionrecord",
            index=models.Index(fields=["next_due_date"], name="sales_dispu_next_du_ff3204_idx"),
        ),
    ]
