# Generated by Django 6.0.2 on 2026-03-13 05:46

import apps.legal_research.models.result
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_remove_is_preferred'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalResearchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='weike', max_length=32, verbose_name='数据源')),
                ('keyword', models.CharField(max_length=255, verbose_name='检索关键词')),
                ('case_summary', models.TextField(verbose_name='案情简述')),
                ('target_count', models.PositiveIntegerField(default=3, verbose_name='目标案例数')),
                ('max_candidates', models.PositiveIntegerField(default=30, verbose_name='最大扫描案例数')),
                ('min_similarity_score', models.FloatField(default=0.65, verbose_name='最低相似度')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度百分比')),
                ('scanned_count', models.PositiveIntegerField(default=0, verbose_name='已扫描数')),
                ('matched_count', models.PositiveIntegerField(default=0, verbose_name='已命中数')),
                ('candidate_count', models.PositiveIntegerField(default=0, verbose_name='候选总数')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='状态说明')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('llm_backend', models.CharField(default='siliconflow', max_length=64, verbose_name='LLM后端')),
                ('llm_model', models.CharField(blank=True, max_length=128, verbose_name='LLM模型')),
                ('q_task_id', models.CharField(blank=True, max_length=64, verbose_name='DjangoQ任务ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_research_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_research_tasks', to='organization.accountcredential', verbose_name='站点账号')),
            ],
            options={
                'verbose_name': '案例检索任务',
                'verbose_name_plural': '案例检索任务',
            },
        ),
        migrations.CreateModel(
            name='LegalResearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='命中顺序')),
                ('source_doc_id', models.CharField(max_length=255, verbose_name='源文档ID')),
                ('source_url', models.TextField(blank=True, verbose_name='源链接')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='标题')),
                ('court_text', models.CharField(blank=True, max_length=255, verbose_name='法院')),
                ('document_number', models.CharField(blank=True, max_length=255, verbose_name='案号')),
                ('judgment_date', models.CharField(blank=True, max_length=64, verbose_name='裁判日期')),
                ('case_digest', models.TextField(blank=True, verbose_name='摘要')),
                ('similarity_score', models.FloatField(default=0.0, verbose_name='相似度分数')),
                ('match_reason', models.TextField(blank=True, verbose_name='匹配理由')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.legal_research.models.result._result_pdf_upload_to, verbose_name='PDF文件')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='legal_research.legalresearchtask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '案例检索结果',
                'verbose_name_plural': '案例检索结果',
                'ordering': ['rank', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='legalresearchtask',
            index=models.Index(fields=['status', '-created_at'], name='legal_resea_status_65ce1b_idx'),
        ),
        migrations.AddIndex(
            model_name='legalresearchtask',
            index=models.Index(fields=['credential', '-created_at'], name='legal_resea_credent_f5c103_idx'),
        ),
        migrations.AddIndex(
            model_name='legalresearchtask',
            index=models.Index(fields=['created_by', '-created_at'], name='legal_resea_created_b206de_idx'),
        ),
        migrations.AddIndex(
            model_name='legalresearchresult',
            index=models.Index(fields=['task', 'rank'], name='legal_resea_task_id_c23290_idx'),
        ),
        migrations.AddIndex(
            model_name='legalresearchresult',
            index=models.Index(fields=['task', 'source_doc_id'], name='legal_resea_task_id_c9b214_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalresearchresult',
            constraint=models.UniqueConstraint(fields=('task', 'source_doc_id'), name='uniq_legal_research_task_source_doc'),
        ),
    ]
