# Generated by Django 6.0.2 on 2026-03-13 06:19

import apps.legal_research.models.result
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalresearchresult',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.legal_research.models.result._result_pdf_upload_to, verbose_name='PDF文件'),
        ),
    ]
