# Generated by Django 6.0.2 on 2026-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_research", "0002_alter_legalresearchresult_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalresearchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("queued", "排队中"),
                    ("running", "执行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=16,
                verbose_name="状态",
            ),
        ),
    ]
