# Generated by Django 6.0.2 on 2026-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0003_alter_legalresearchtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalresearchtask',
            name='max_candidates',
            field=models.PositiveIntegerField(default=100, verbose_name='最大扫描案例数'),
        ),
        migrations.AlterField(
            model_name='legalresearchtask',
            name='min_similarity_score',
            field=models.FloatField(default=0.9, verbose_name='最低相似度'),
        ),
    ]
