# Generated by Django 6.0.2 on 2026-03-13 10:01

import uuid
import django.db.models.deletion
from django.db import migrations, models


def _prepare_numeric_ids(apps, schema_editor) -> None:
    task_table = schema_editor.quote_name("legal_research_legalresearchtask")
    result_table = schema_editor.quote_name("legal_research_legalresearchresult")
    task_map_table = schema_editor.quote_name("legal_research_task_id_map_tmp")
    result_map_table = schema_editor.quote_name("legal_research_result_id_map_tmp")

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            CREATE TEMP TABLE {task_map_table} AS
            SELECT id AS old_id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS new_id
            FROM {task_table}
            """
        )
        cursor.execute(
            f"""
            CREATE TEMP TABLE {result_map_table} AS
            SELECT id AS old_id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS new_id
            FROM {result_table}
            """
        )

        # 保存旧 UUID，便于追溯历史记录。
        cursor.execute(f"UPDATE {task_table} SET legacy_uuid = id")
        cursor.execute(f"UPDATE {result_table} SET legacy_uuid = id")

        # 先替换父表主键，再同步子表外键，最后替换子表主键。
        cursor.execute(
            f"""
            UPDATE {task_table}
            SET id = CAST((SELECT new_id FROM {task_map_table} WHERE old_id = {task_table}.id) AS TEXT)
            """
        )
        cursor.execute(
            f"""
            UPDATE {result_table}
            SET task_id = CAST((SELECT new_id FROM {task_map_table} WHERE old_id = {result_table}.task_id) AS TEXT)
            """
        )
        cursor.execute(
            f"""
            UPDATE {result_table}
            SET id = CAST((SELECT new_id FROM {result_map_table} WHERE old_id = {result_table}.id) AS TEXT)
            """
        )

        cursor.execute(f"DROP TABLE {task_map_table}")
        cursor.execute(f"DROP TABLE {result_map_table}")


class Migration(migrations.Migration):
    dependencies = [
        ("legal_research", "0004_alter_legalresearchtask_max_candidates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalresearchresult",
            name="legacy_uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="历史UUID"),
        ),
        migrations.AddField(
            model_name="legalresearchtask",
            name="legacy_uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="历史UUID"),
        ),
        migrations.RunPython(_prepare_numeric_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="legalresearchtask",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="legalresearchresult",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="legalresearchresult",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="legal_research.legalresearchtask",
                verbose_name="任务",
            ),
        ),
    ]
