# Generated by Django 6.0.2 on 2026-03-15 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0005_legalresearchresult_legacy_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalResearchTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('search', '检索'), ('detail', '详情')], db_index=True, max_length=32, verbose_name='阶段')),
                ('source', models.CharField(choices=[('api', 'API'), ('dom', 'DOM'), ('system', '系统')], db_index=True, max_length=16, verbose_name='来源')),
                ('interface_name', models.CharField(max_length=64, verbose_name='接口名')),
                ('method', models.CharField(blank=True, max_length=12, verbose_name='请求方法')),
                ('url', models.TextField(blank=True, verbose_name='请求URL')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='状态码')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时(ms)')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='错误码')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='错误消息')),
                ('request_summary', models.JSONField(blank=True, default=dict, verbose_name='请求摘要')),
                ('response_summary', models.JSONField(blank=True, default=dict, verbose_name='返回摘要')),
                ('event_metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='legal_research.legalresearchtask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '案例检索事件',
                'verbose_name_plural': '案例检索事件',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['task', 'stage', 'created_at'], name='legal_resea_task_id_5faf0b_idx'), models.Index(fields=['task', 'source', 'created_at'], name='legal_resea_task_id_4ab902_idx'), models.Index(fields=['task', 'interface_name', 'created_at'], name='legal_resea_task_id_b2e587_idx')],
            },
        ),
    ]
