# Generated by Django 6.0.2 on 2026-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0006_legalresearchtaskevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalresearchtask',
            name='search_mode',
            field=models.CharField(choices=[('expanded', '扩展检索'), ('single', '单检索')], default='expanded', max_length=16, verbose_name='检索模式'),
        ),
    ]
