# Generated by Django 6.0.2 on 2026-03-19 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_research", "0007_legalresearchtask_search_mode"),
        ("organization", "0002_remove_is_preferred"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseDownloadTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_numbers", models.TextField(verbose_name="案号列表")),
                (
                    "file_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("doc", "Word")], default="pdf", max_length=8, verbose_name="文件格式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("queued", "排队中"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0, verbose_name="总案例数")),
                ("success_count", models.PositiveIntegerField(default=0, verbose_name="成功数")),
                ("failed_count", models.PositiveIntegerField(default=0, verbose_name="失败数")),
                ("message", models.CharField(blank=True, max_length=255, verbose_name="状态说明")),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                ("q_task_id", models.CharField(blank=True, max_length=64, verbose_name="DjangoQ任务ID")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_download_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_download_tasks",
                        to="organization.accountcredential",
                        verbose_name="站点账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "案例下载任务",
                "verbose_name_plural": "案例下载任务",
            },
        ),
        migrations.CreateModel(
            name="CaseDownloadResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_number", models.CharField(max_length=255, verbose_name="案号")),
                ("title", models.CharField(blank=True, max_length=500, verbose_name="案例标题")),
                ("court", models.CharField(blank=True, max_length=255, verbose_name="法院")),
                ("judgment_date", models.CharField(blank=True, max_length=32, verbose_name="裁判日期")),
                ("file_path", models.CharField(max_length=1024, verbose_name="文件路径")),
                ("file_size", models.PositiveIntegerField(default=0, verbose_name="文件大小")),
                (
                    "file_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("doc", "Word")], default="pdf", max_length=8, verbose_name="文件格式"
                    ),
                ),
                ("status", models.CharField(default="success", max_length=16, verbose_name="状态")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("downloaded_at", models.DateTimeField(auto_now_add=True, verbose_name="下载时间")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="legal_research.casedownloadtask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "案例下载结果",
                "verbose_name_plural": "案例下载结果",
            },
        ),
        migrations.AddIndex(
            model_name="casedownloadtask",
            index=models.Index(fields=["status", "-created_at"], name="legal_resea_status_1d730f_idx"),
        ),
        migrations.AddIndex(
            model_name="casedownloadtask",
            index=models.Index(fields=["credential", "-created_at"], name="legal_resea_credent_498960_idx"),
        ),
        migrations.AddIndex(
            model_name="casedownloadtask",
            index=models.Index(fields=["created_by", "-created_at"], name="legal_resea_created_35e6c2_idx"),
        ),
        migrations.AddIndex(
            model_name="casedownloadresult",
            index=models.Index(fields=["task", "case_number"], name="legal_resea_task_id_889c3f_idx"),
        ),
    ]
