# Generated by Django 6.0.3 on 2026-03-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_research", "0008_case_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalresearchtask",
            name="advanced_query",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='JSON 数组，例如：[{"field":"courtOpinion","keyword":"逾期利息","op":"AND"}]',
                verbose_name="高级检索条件",
            ),
        ),
        migrations.AddField(
            model_name="legalresearchtask",
            name="cause_of_action_filter",
            field=models.CharField(blank=True, max_length=128, verbose_name="案由筛选"),
        ),
        migrations.AddField(
            model_name="legalresearchtask",
            name="court_filter",
            field=models.CharField(blank=True, max_length=128, verbose_name="法院筛选"),
        ),
        migrations.AddField(
            model_name="legalresearchtask",
            name="date_from",
            field=models.CharField(blank=True, max_length=10, verbose_name="裁判日期起"),
        ),
        migrations.AddField(
            model_name="legalresearchtask",
            name="date_to",
            field=models.CharField(blank=True, max_length=10, verbose_name="裁判日期止"),
        ),
    ]
