# Generated by Django 6.0.2 on 2026-03-25 21:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfSplittingTool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Pdf Splitting", max_length=64)),
            ],
            options={
                "verbose_name": "PDF 拆解",
                "verbose_name_plural": "PDF 拆解",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PdfSplitJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("upload", "上传文件"), ("local_path", "本地路径")],
                        max_length=16,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "source_abs_path",
                    models.CharField(blank=True, default="", max_length=2048, verbose_name="源绝对路径"),
                ),
                (
                    "source_relpath",
                    models.CharField(blank=True, default="", max_length=1024, verbose_name="源相对路径"),
                ),
                ("source_original_name", models.CharField(max_length=255, verbose_name="源文件名")),
                ("template_key", models.CharField(default="filing_materials_v1", max_length=64, verbose_name="模板键")),
                ("template_version", models.CharField(default="1", max_length=32, verbose_name="模板版本")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("review_required", "待复核"),
                            ("exporting", "导出中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("total_pages", models.PositiveIntegerField(default=0, verbose_name="总页数")),
                ("processed_pages", models.PositiveIntegerField(default=0, verbose_name="已处理页数")),
                ("progress", models.PositiveIntegerField(default=0, verbose_name="进度")),
                ("current_page", models.PositiveIntegerField(default=0, verbose_name="当前页")),
                ("task_id", models.CharField(blank=True, default="", max_length=64, verbose_name="任务ID")),
                ("cancel_requested", models.BooleanField(default=False, verbose_name="请求取消")),
                ("summary_payload", models.JSONField(blank=True, default=dict, verbose_name="摘要")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                (
                    "export_zip_relpath",
                    models.CharField(blank=True, default="", max_length=1024, verbose_name="导出ZIP路径"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pdf_split_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF 拆解任务",
                "verbose_name_plural": "PDF 拆解任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PdfSplitSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="排序")),
                ("page_start", models.PositiveIntegerField(verbose_name="起始页")),
                ("page_end", models.PositiveIntegerField(verbose_name="结束页")),
                (
                    "segment_type",
                    models.CharField(
                        choices=[
                            ("complaint", "起诉状"),
                            ("evidence_list", "证据清单及明细"),
                            ("preservation_materials", "财产保全资料"),
                            ("party_identity", "双方当事人主体信息"),
                            ("authorization_materials", "授权委托材料"),
                            ("delivery_address_confirmation", "送达地址确认书"),
                            ("refund_account_confirmation", "诉讼费用退费账户确认书"),
                            ("unrecognized", "未识别材料"),
                        ],
                        default="unrecognized",
                        max_length=48,
                        verbose_name="段类型",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                ("confidence", models.FloatField(default=0.0, verbose_name="置信度")),
                ("source_method", models.CharField(default="rule", max_length=32, verbose_name="来源方法")),
                (
                    "review_flag",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("low_confidence", "低置信度"),
                            ("unrecognized", "未识别"),
                            ("ocr_failed", "OCR失败"),
                        ],
                        default="normal",
                        max_length=32,
                        verbose_name="复核标记",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="pdf_splitting.pdfsplitjob",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF 拆解片段",
                "verbose_name_plural": "PDF 拆解片段",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="pdfsplitjob",
            index=models.Index(fields=["status", "-created_at"], name="pdf_splitti_status_15aaad_idx"),
        ),
        migrations.AddIndex(
            model_name="pdfsplitjob",
            index=models.Index(fields=["created_by", "-created_at"], name="pdf_splitti_created_d4c84a_idx"),
        ),
        migrations.AddConstraint(
            model_name="pdfsplitsegment",
            constraint=models.UniqueConstraint(fields=("job", "order"), name="pdf_splitting_segment_job_order_uniq"),
        ),
    ]
