# Generated by Django 6.0.2 on 2026-03-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_splitting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfsplitjob",
            name="ocr_profile",
            field=models.CharField(
                choices=[("fast", "快速"), ("balanced", "均衡"), ("accurate", "高精度")],
                default="balanced",
                max_length=16,
                verbose_name="OCR 档位",
            ),
        ),
    ]
