# Generated by Django 6.0.2 on 2026-03-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_splitting", "0002_pdfsplitjob_ocr_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfsplitjob",
            name="split_mode",
            field=models.CharField(
                choices=[("content_analysis", "内容识别拆分"), ("page_split", "按页拆分")],
                default="content_analysis",
                max_length=32,
                verbose_name="拆分模式",
            ),
        ),
    ]
