# Generated by Django 6.0.3 on 2026-03-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_splitting", "0003_pdfsplitjob_split_mode"),
    ]

    operations = []
