# Generated by Django 6.0.3 on 2026-03-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_splitting', '0004_add_manual_split_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfsplitjob',
            name='split_mode',
            field=models.CharField(choices=[('content_analysis', '内容识别拆分'), ('page_split', '按页拆分'), ('manual_split', '手动拆分')], default='content_analysis', max_length=32, verbose_name='拆分模式'),
        ),
    ]
